### ISSUE TITLE
Reply-to-reply is not reply to original

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy#813] opened 2018-04-18 19:06 UTC
Brid.gy from Facebook sends me webmentions for comments on comments on comments on my posts. This is great and exactly what I want. However, it marks both the parent comment *and* the root post as `u-in-reply-to` -- this makes it confusing when trying to build the whole conversation tree, since the comment basically declares that it should be grafted at two points in the tree.

Suggestion: keep all links, but only mark the one to actual parent as `u-in-reply-to`

**Comment by snarfed** [comment] 2018-04-18 19:30
heh, true! this is technically incorrect...but still pretty much necessary, for a number of reasons:

* most silo comments-on-comments are replies to other silo comments, not to your own POSSED comments. if we mirror that strictly correctly, there won't be a link to your site at all, so the webmention would be invalid.
* many sites don't include replies in their home page feed or linked `rel=feed`s. for those sites, bridgy's original post discovery wouldn't find POSSEd comments, so it wouldn't know the original comment permalink on your site to link to.
* bridgy users generally want the whole conversation on a post to show up on that post. the vast majority of indieweb CMSes (notably Known and WordPress) don't do this kind of dynamic threading - permalink per comment, but also render them all together on the original post - well or at all. so if we did this, they'd break.

[salmentions](https://indieweb.org/salmention) are arguably the best answer to this. with salmentions, bridgy comments-on-comments could `in-reply-to`-link to the bridgy URL for the parent comment, and propagate salmentions all the way up to the original post. sadly, implementing salmentions well is tricky and subtle, so they haven't seen much development or adoption so far. still, that might be the best place to push forward if you're interested in this! more details in #458.

**Comment by singpolyma** [comment] 2018-04-18 19:57
That's why I wouldn't want to remove the link to the parent post -- I only want to remove the implication that this is a reply to that. It'll still validate as a webmention and get picked up by the target site, but as a mention instead of a reply (since that's what it is).

**Comment by singpolyma** [comment] 2018-04-18 19:58
salmention makes a lot of weird assumptions (such as that everyone puts a comment fed on the post page) -- I actually much prefer the way bridgy works now, just with the one small tweak.

**Comment by snarfed** [comment] 2018-04-18 20:56
> That's why I wouldn't want to remove the link to the parent post -- I only want to remove the implication that this is a reply to that. It'll still validate as a webmention and get picked up by the target site, but as a mention instead of a reply (since that's what it is).

ah, thanks! sorry, missed that part.

definitely makes more sense. the drawback is that wordpress and (i think) known both render mentions as _X mentioned this on site.com_ by default, instead of rendering the actual contents, which would be too big of a regression in functionality for most users for me to ship.

**Comment by singpolyma** [comment] 2018-04-18 23:28
Hmm... what if, for now, you add a second class to all the indirect parents `thread-parent` or something? Then I can at least specifically support brid.gy when building threads.

**Comment by snarfed** [comment] 2018-04-18 23:49
sure! alternatively, if you get a wm with multiple `u-in-reply-to`s, your CMS already knows which ones are and aren't root posts, though, right? so you can probably do this now as is, without a new class...? i'm happy to add (or merge a PR that adds 😁) the new class too though.

**Comment by snarfed** [comment] 2018-04-24 13:37
hey @singpolyma do you have an example of this handy?

**Comment by singpolyma** [comment] 2018-04-25 00:46
https://brid-gy.appspot.com/comment/facebook/515373050/10155685063888051/10155685063888051_10155702316318051

I recently discovered the `?format=json` version as well... I may actually prefer to use that for my purposes, but then the extra class hack won't exactly help there... I'll keep thinking.

**Comment by snarfed** [comment] 2018-04-25 01:01
thanks! ...but hmm, i'm not sure that's actually an example. it has:

```html
<a class="u-in-reply-to" href="https://www.facebook.com/515373050/posts/10155685063888051"></a>
<a class="u-in-reply-to" href="https://www.facebook.com/515373050/posts/10155685063888051?comment_id=10155686423343051"></a>
<a class="u-in-reply-to" href="https://singpolyma.net/actionstream/travelling-to-boston-tomorrow/"></a>
<a class="u-in-reply-to" href="http://sngpl.ma/t4tY0"></a>
```

only the last two are useful to you, and https://singpolyma.net/actionstream/travelling-to-boston-tomorrow/ says that http://sngpl.ma/t4tY0 is its shortlink, so there's only one actual post on your site that this is `in-reply-to`. right?

(unrelated note, looks like sngpl.ma no longer actually serves your shortlinks. :P)

**Comment by singpolyma** [comment] 2018-04-25 01:05
But the point is that this *isn't* `in-reply-to` *anything* on my site, but rather a reply to `https://www.facebook.com/515373050/posts/10155685063888051?comment_id=10155686423343051`

The reason this matters is that I'm working on building the entire conversation tree wherever possible.

Also: `http://sngpl.ma/t4tY0` is working here in browser and in cURL -- what does it do for you?

**Comment by snarfed** [comment] 2018-04-25 06:26
sure, i understand. so you look for a comment's `in-reply-to`s in both your own post permalinks and in `u-url`s for comments you've received, and that's how you find where to attach it?

i can definitely work on identifying just the root post and adding a class to it. almost always though, it would be the only link to your site, and the other link(s) to silo URLs would be the intermediate comment(s).

how about this heuristic? if a comment is `in-reply-to` both a root post on your site and another comment on that post, attach it to the comment, not to the root post.

> Also: http://sngpl.ma/t4tY0 is working here in browser and in cURL -- what does it do for you?

ah. it does work on http, but on https it serves your xmpp server instead. i use https everywhere, so i see that in my browser even for http URLs, but elsewhere they work fine.

**Comment by snarfed** [comment] 2020-01-27 23:08
> how about this heuristic? if a comment is `in-reply-to` both a root post on your site and another comment on that post, attach it to the comment, not to the root post.

@singpolyma, friendly nudge! are you still using bridgy and interested in this issue? would this heuristic work for you?

**Comment by snarfed** [comment] 2020-05-03 21:44
tentatively closing. feel free to reopen!

**Closed** 2020-05-03 21:44 UTC
Labels: listen

**Comment by jpcaruana** [comment] 2022-02-04 16:28
Hi quick question here: is my issue related to this github thread ? In this tweeter conversation, I had responses from the author in a series of tweets, but only the first one generated a webmention back to my website (see log https://brid.gy/log?start_time=1643991356&amp;key=agdicmlkLWd5cjYLEghSZXNwb25zZSIodGFnOnR3aXR0ZXIuY29tLDIwMTM6MTQ4OTYyNzQzNzgzOTM5Mjc3MAw). Thanks.

(Originally published at: https://jp.caruana.fr/notes/2022/02/04/hi-quick-question-here-is-my/)

**Comment by snarfed** [comment] 2022-02-04 21:07
Hi @jpcaruana, sorry for the trouble! This issue is a different one than yours. Your issue is probably just that Bridgy's Twitter support is best effort, sadly, since their v1 API doesn't directly support fetching reply chains, so we have to do it manually, indirectly. More info in https://brid.gy/about#Twitter+responses

**Comment by jpcaruana** [comment] 2022-02-08 17:51
Very clear, thank you @snarfed
