### ISSUE TITLE
Post with u-photo has access error

### ISSUE THREAD

**Issue by jackysee** [snarfed/bridgy#779] opened 2017-12-01 03:38 UTC
Post: https://jacky.seezone.net/2017/12/01/9546/
Log: https://brid.gy/log?start_time=1512098825&key=aglzfmJyaWQtZ3lyUQsSDVB1Ymxpc2hlZFBhZ2UiKmh0dHBzOi8vamFja3kuc2Vlem9uZS5uZXQvMjAxNy8xMi8wMS85NTQ2LwwLEgdQdWJsaXNoGICAgICA8ogKDA

The post manually published in brid.gy, preview is OK. So the image is at least accessible through browser.

I tried another one [here](https://brid.gy/log?start_time=1512098522&key=aglzfmJyaWQtZ3lyUQsSDVB1Ymxpc2hlZFBhZ2UiKmh0dHBzOi8vamFja3kuc2Vlem9uZS5uZXQvMjAxNy8xMi8wMS85NTQzLwwLEgdQdWJsaXNoGICAgICAgIAKDA) using image from placehold.it which can be posted successfully. 

So it may relate to my host setting, but it's just cloudflare at the front. Based on `The owner of this website has banned your access based on your browser's signature ... `, may be it's related to user-agent string?

**Comment by snarfed** [comment] 2017-12-01 05:35
hey jacky, thanks for the detailed sleuthing! yup, looks like cloudflare is blocking bridgy's http request for your image and returning 403.

your guys is probably good. i expect it's it's user agent and/or client IP. maybe see if you can find cloudflare's blocking settings and relax them?

**Comment by jackysee** [comment] 2017-12-01 07:20
yes, it's probably the agent
with this test code, I can get it work
```
from urllib.request import Request, urlopen
url = 'https://jacky.seezone.net/wp-content/uploads/2017/12/cats2_0152.jpg'
req = Request(url, headers = {'User-Agent': 'Mozilla/5.0'});
html = urlopen(req).read()
print(html)
```
For the cloudflare setting, I have to contact another admin to check.

**Comment by snarfed** [comment] 2017-12-13 14:45
tentatively closing since cloudflare's config is the root cause. @jackysee feel free to reopen if this is still a problem!

**Closed by snarfed** 2017-12-13 14:45 UTC
