### ISSUE TITLE
Seems Facebook mentions have stopped again

### ISSUE THREAD

**Issue by armingrewe** [snarfed/bridgy#826] opened 2018-05-25 11:33 UTC
Haven't had time to check anything (and am on phone only for now), but it looks like Facebook mentions stopped working some time last night. Just as Twitter started to work again...

**Comment by snarfed** [comment] 2018-05-25 14:30
hey armin! hmm, facebook backfeed is definitely still working for at least some users, eg https://brid.gy/facebook/10206605282077198 and https://brid.gy/facebook/508178999257997 .

what's your bridgy user page?

**Comment by armingrewe** [comment] 2018-05-25 14:36
Should be this one for Facebook: https://brid.gy/facebook/776938267

Twitter still works fine, but FB stopped at some point. I know there have been a few likes of the picture I posted this morning, about 8 hours ago. Last one picked up was for yesterday's picture about 22 hours ago.

**Comment by snarfed** [comment] 2018-05-25 14:45
thanks! agreed, your latest two posts are missing.

suspicious that it stopped working (for you at least) precisely on GDPR day. although the other two working examples are in the EU too, so who knows.

regardless, sorry for the trouble! i'll look into it.

**Comment by snarfed** [comment] 2018-05-25 20:50
another report: https://twitter.com/thorkon/status/1000113381297270784

**Comment by snarfed** [comment] 2018-05-26 15:30
no consistent difference in the FB access token permissions for these accounts.

working: https://brid.gy/facebook/508178999257997
`user_photos, user_status, user_posts, manage_pages, pages_show_list, business_management, public_profile`

working: https://brid.gy/facebook/10206605282077198
`user_photos, user_status, user_posts, manage_pages, pages_show_list, business_management, public_profile`

broken: https://brid.gy/facebook/776938267 (armin)
`user_photos, user_status, user_posts, manage_pages, pages_show_list, public_profile`

broken: https://brid.gy/facebook/555706984828608 (thorkon)
`user_photos, user_status, user_posts, manage_pages, pages_show_list, publish_pages, business_management, public_profile`

**Comment by snarfed** [comment] 2018-05-26 17:26
hey @armingrewe could you try logging into Facebook on https://brid.gy/ again? probably won't fix it, but worth a shot.

**Comment by armingrewe** [comment] 2018-05-26 17:39
Sure. Just done, disabled and logged in again. Sadly doesn't seem to have made any difference (so far).

I so wish I could dump Facebook, unfortunately there are so many of my friends on there who won't touch Twitter or G+.

**Comment by snarfed** [comment] 2018-05-27 14:47
looks like this is actually affecting everyone after all. the accounts i thought were working, eg https://brid.gy/facebook/10206605282077198 , are actually only getting their own comments and likes, not other people's.

specifically `/v2.10/me/feed?...` is returning everyone's posts ok, but only their own responses. or maybe only bridgy users'; not sure.

(interestingly https://brid.gy/facebook/508178999257997 is getting everything, but it's a FB page, not a user, which i expect is the difference.)

regardless, i expect the fix is #814...except facebook claims we have until august 1 to resubmit for approval, so i'm not entirely sure this is that.

**Comment by snarfed** [comment] 2018-05-27 15:01
i actually now wonder if this is a facebook bug, specifically https://developers.facebook.com/support/bugs/721093238281702/

lots more reports of this there, and FB hasn't yet concluded said it's due to permissions. search for eg `comments likes` on https://developers.facebook.com/support/bugs/ (the search box under _Other Platform Bug Reports_, not the top one). eg https://developers.facebook.com/support/bugs/1627371787379210/ .

**Comment by armingrewe** [comment] 2018-05-27 15:08
The timing looks about right, they both say it started Thu/Fri if I read it right, which would be the same time as bridgy not getting them any more.

**Comment by snarfed** [comment] 2018-05-30 16:46
woo, progress, of a sort. [facebook confirmed and said they're investigating.](https://developers.facebook.com/support/bugs/721093238281702/)

> Thanks for clarifying this. We've managed to repro this problem. We're assigning this to our product team for further investigation.

**Comment by snarfed** [comment] 2018-05-31 15:56
sigh. looks like it is permissions after all. another update from FB today:

> Sorry for the confusion.
>
> This is intentional and due to the changes we announced here - https://developers.facebook.com/blog/post/2018/05/01/facebook-login-updates-further-protect-privacy/
>
> Specifically:
>
> > Additionally, other users' profile information and comments will not be returned when accessing user posts, photos, albums, videos, likes, and reactions unless authorized by those users. These changes are effective immediately for new apps. Apps created before May 1, 2018 will continue to have access to this data until May 24, 2018.

this may mean the end of Facebook backfeed. 😱

**Comment by armingrewe** [comment] 2018-05-31 21:18
Very much looks like it. Must admit I don't understand the "unless authorized by those users" part. How would they do that? Can't think of a setting in Facebook to do that.
Well, apparently [Generation Z is killing Facebook anyway](http://uk.businessinsider.com/generation-z-things-gen-z-are-killing-facebook-ralph-lauren-2018-5?r=US&IR=T), so might not be a big loss ;-)

**Comment by nekr0z** [comment] 2018-06-01 07:02
So basically Facebook comments import is screwed for good from now on?

**Comment by snarfed** [comment] 2018-06-01 13:52
very possibly yes. 😢

**Comment by snarfed** [comment] 2018-06-03 05:07
m.facebook.com doesn't work, it doesn't serve posts unless you're signed in. and that was my last idea. if anyone else has any ideas, feel free to speak up! otherwise i expect I'll write bridgy facebook's obituary and turn it off.

**Comment by armingrewe** [comment] 2018-06-03 09:42
My suspicion is that after the Cambridge Analytica scandal they are going to lock this down fairly hard and any way you find around it will only be short lived.

**Comment by snarfed** [comment] 2018-06-04 14:12
i used this `remote_api_shell` snippet to send FB notifications to all bridgy listen users, based on #817:

```sh
$ setenv FACEBOOK_APP_ID `cat facebook_app_id`
$ setenv FACEBOOK_APP_SECRET `cat facebook_app_secret`
$ remote_api_shell.py brid-gy
```
```py
import traceback
from facebook import FacebookPage

for src in FacebookPage.query(
    FacebookPage.status == 'enabled',
    FacebookPage.features == 'listen',
  ):
  if src.auth_entity.get().type == 'user':
    print(src.label(), src.silo_url())
    try:
      src.gr_source.create_notification(
        src.key.id(),
        "Facebook has disabled the API support Bridgy needs, so we're turning off Faceook support. So long, and thanks for all the fish!",
        'https://brid.gy/about#facebook-listen')
    except Exception as e:
      traceback.print_exc()
```

**Comment by snarfed** [comment] 2018-06-04 17:22
82d0b0cc9f9b6c3c30d0b04255636b9b0326a0b4

**Comment by snarfed** [comment] 2018-06-05 03:06
@singpolyma not immediately, no, but Facebook is turning off API publish support in August too, independently: #817

**Comment by armingrewe** [comment] 2018-06-05 14:23
I'll leave you to close this one once you're happy that the big clean up you unfortunately have to go through is finished.

**Comment by snarfed** [comment] 2018-06-09 15:35
so long, and thanks for all the fish! https://snarfed.org/2018-06-07_turning-off-facebook-for-bridgy

**Closed** 2018-06-09 15:35 UTC
Labels: listen
