### ISSUE TITLE
Facebook internal bug incorrectly replaces years in links with FB user ids

### ISSUE THREAD

**Issue by kylewm** [snarfed/bridgy#368] opened 2015-02-25 02:03 UTC
For example backfeeding a like on the post https://www.facebook.com/12802152/posts/10101222294987969 has 

```
<a class="u-like u-like-of" href="https://kylewm.com/10101859667632951/02/can-t-believe-i-ve-never-seen-this-before-carl-sagan"></a>
```
- https://brid-gy.appspot.com/like/facebook/12802152/10101222294987969/434717353347341

whereas the correct URL should be https://kylewm.com/2015/02/can-t-believe-i-ve-never-seen-this-before-carl-sagan

somehow a random FB ID is sneaking into my permalink??

**Comment by snarfed** [comment] 2015-02-25 04:59
holy what the I don't even... wow. that's a weird symptom. no clue what's going on, but nice catch!

**Comment by kylewm** [comment] 2015-02-25 15:48
no way, it comes from the FB API like this. have to admit that's kind of funny.

[/v2.2/12802152_10101222294987969](https://developers.facebook.com/tools/explorer/145634995501895/?method=GET&path=12802152_10101222294987969&version=v2.2&)

```json
{
  "id": "12802152_10101222294987969",
  "from": {
    "id": "12802152",
    "name": "Kyle Mahan"
  },
  "message": "Can’t believe I’ve never seen this before Carl Sagan - Who Speaks for Earth. Hard to believe it’s from 35 years ago https://www.youtube.com/watch?v=HjrmK8t6VYk",
  "actions": [
    {
      "name": "Comment",
      "link": "https://www.facebook.com/12802152/posts/10101222294987969"
    },
    {
      "name": "Like",
      "link": "https://www.facebook.com/12802152/posts/10101222294987969"
    },
    {
      "name": "See Original",
      "link": "https://kylewm.com/10101343067483791/02/can-t-believe-i-ve-never-seen-this-before-carl-sagan"
    }
  ], 
```

**Comment by kylewm** [comment] 2015-02-25 15:59
oh hilarious, it's the 10101343067483791 is the app-scoped user id for facebook.com/2015

**Comment by snarfed** [comment] 2015-02-25 18:11
ahahaha everybody poops, even facebook. thanks for tracking it down.

**Comment by snarfed** [comment] 2015-02-27 00:27
oh btw @kylewm, if you can think of a workaround for this in bridgy or a-u, i say go for it.

**Comment by kylewm** [comment] 2015-02-27 16:03
I mean, we could hard code the app-ids for 2010-2030 or something, but I don't really want to go there.

**Comment by kylewm** [comment] 2015-03-01 23:43
@benwerd unfortunately, this may be relevant to your interests... see for example the "See Original" link on your post https://developers.facebook.com/tools/explorer/145634995501895/?method=GET&path=36802236_10101087679224279&version=v2.2&

```
{
  "id": "36802236_10101087679224279",
  "from": {
    "id": "36802236",
    "name": "Ben Werdmüller"
  },
  "message": "I can't find one: is there a UK equivalent to TaskRabbit that serves Oxford?",
  "actions": [
    {
      "name": "Comment",
      "link": "https://www.facebook.com/36802236/posts/10101087679224279"
    },
    {
      "name": "Like",
      "link": "https://www.facebook.com/36802236/posts/10101087679224279"
    },
    {
      "name": "See Original",
      "link": "http://werd.io/10101343067483791/i-cant-find-one-is-there-a-uk-equivalent-to"
    }
  ], 
```

**Comment by snarfed** [comment] 2015-03-01 23:50
hah, funny, known evidently ignores that first numeric path element, which works around the problem. ie these urls all find the post correctly:

* http://werd.io/2015/i-cant-find-one-is-there-a-uk-equivalent-to
* http://werd.io/10101343067483791/i-cant-find-one-is-there-a-uk-equivalent-to
* http://werd.io/0/i-cant-find-one-is-there-a-uk-equivalent-to

**Comment by benwerd** [comment] 2015-03-02 00:01
/me whistles nonchalantly

This is absolutely correct, but is not guaranteed to be true in the future. But, yay, Facebook handles numbers terribly too *hands in the air*

**Comment by snarfed** [comment] 2015-09-01 19:49
looks like this is currently happening to @cleverdevil too. facebook is converting his original post URL `https://cleverdevil.io/2015/laying-in-bed-with-the-entire-family-after-a-tough` to `https://cleverdevil.io/10101859667632951/laying-in-bed-with-the-entire-family-after-a-tough`.

* https://www.brid.gy/facebook/10101418101899349
* https://cleverdevil.io/2015/laying-in-bed-with-the-entire-family-after-a-tough
* https://www.facebook.com/10101418101899349/posts/10101448030806579
* https://www.brid.gy/log?start_time=1441134125&key=aglzfmJyaWQtZ3lyUAsSCFJlc3BvbnNlIkJ0YWc6ZmFjZWJvb2suY29tLDIwMTM6MTAxMDE0NDgwMzA4MDY1NzlfbGlrZWRfYnlfMTAyMDYzMjI0NjA2MzM1MjQM

**Comment by snarfed** [comment] 2015-09-01 19:50
this is a facebook bug, so it's a bit hard for us to work around. i'm reopening and updating the title so that we can at least find this easier.

**Comment by kylewm** [comment] 2015-09-01 20:13
We should assume FB's "See Original" support is going away since it is undocumented and was recently removed from their UI. We still get it from the API as metadata, but I suspect that is just an oversight on FB's part, and they'll stop sending it eventually/unexpectedly.

Unfortunately, since posse-post-discovery is very hard for Facebook posts (#375), this means that publishers will need to start including their original post URL some other way, maybe in the *body* of the post.

BTW, photos posted directly from Instagram app to Facebook have the post permalink in the header, instead of the typical application URL, we should look into whether our sites (Known, Bridgy Publish, Red Wind) can use this same mechanism to replace See Original

![instagram-permalink](https://cloud.githubusercontent.com/assets/950127/9615145/3b55731e-50ab-11e5-877c-392d0684a13e.png)

**Comment by kylewm** [comment] 2015-12-08 07:30
> Somebody should look into whether our sites (Known, Bridgy Publish, Red Wind) can use this same mechanism to replace See Original!

["This is a custom configuration for Instagram"](http://stackoverflow.com/questions/32343041/publish-via-facebook-api-how-to-include-link-to-original-like-instagram-does)

**Comment by snarfed** [comment] 2016-02-11 22:55
@cleverdevil is hitting this again: http://indiewebcamp.com/irc/2016-02-11#t1455231072609

we should see if we can find a workaround.

**Comment by snarfed** [comment] 2016-02-11 23:07
i think i'd reiterate @kylewm's point in https://github.com/snarfed/bridgy/issues/368#issuecomment-136846840 that the root cause here, FB's _See Original_ link, is brittle and not really officially supported. @kylewm @benwerd (@cleverdevil) et al, if Known currently uses it for FB POSSE, maybe consider switching to an attached link or even text link instead? those are both known to work ok right now.

example FB API object below. compare the top-level `link` field, which is correct, and the _See Original_ link, which is broken.

```json
{
  "id": "10101418101899349_10101615455740669"
  "message": "Changing Education Paradigms",
  "link": "https://cleverdevil.io/2016/changing-education-paradigms",
  "actions": [{
    "name": "See Original",
    "link": "https://cleverdevil.io/10102571892817971/changing-education-paradigms"
  }],
  "application": {
    "category": "Utilities",
    "link": "http://cleverdevil.io/",
    "name": "cleverdevil known bridge",
    "id": "1021349254572205"
  },
  "caption": "cleverdevil.io",
  "description": "This year, my daughter made the move from preschool to school, and the transition was quite difficult for her. We initially enrolled her in a",
  "from": {
    "name": "Jonathan LaCour",
    "id": "10101418101899349"
  },
  "type": "link",
  "status_type": "published_story",
}
```

**Comment by kylewm** [comment] 2016-02-11 23:38
keep an eye on https://github.com/idno/Facebook/issues/31

**Comment by snarfed** [comment] 2016-02-12 01:42
woo thanks @kylewm! known plans to stop using _See Original_, which should mostly moot this. we should probably start walking back bridgy's support for it too, and document its problems in the bridgy docs.

**Comment by snarfed** [comment] 2016-02-26 19:29
thanks for merging that known fix @kylewm! tentatively closing this.

**Closed by snarfed** 2016-02-26 19:29 UTC
Labels: listen, now

**Comment by benwerd** [comment] 2016-02-26 19:46
A note here: there's an issue with Convoy / withknown.com wrt the latest syndication code, so it's taking me longer than I'd like to deploy that. Hoping to get it sorted by Monday.

**Comment by snarfed** [comment] 2016-02-26 20:06
no worries @benwerd! not urgent.
