### ISSUE TITLE
Check that URLs are set properly when registering

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy#521] opened 2015-10-23 00:40 UTC
It would be neat if using the "register from my site with callback" feature I could pass in the URL of my site and have brid.gy warn me (or offer to fix it) if my silo profile URL differs.

**Comment by snarfed** [comment] 2015-10-23 00:58
interesting! @kylewm mind triaging this?

**Comment by kylewm** [comment] 2015-10-23 04:38
Sure thing. This was intentionally added without checking because Known
users wanted to register with Bridgy without adding their url to their
silo profile


On Thu, Oct 2owanted , at 05:58 PM, Ryan Barrett wrote:
> interesting! @kylewm[1] mind triaging this?


> — Reply to this email directly or view it on GitHub[2].


>



Links:

  1. https://github.com/kylewm
  2. https://github.com/snarfed/bridgy/issues/521#issuecomment-150397819

**Comment by singpolyma** [comment] 2015-10-23 12:25
Right. For limited backfeed scenarios it doesn't have to be set. But for most backfeed and all publish, I *does* have to be set. So it should be optional, I think, but *if* a post to the hook includes a URL, a warning could be nice :)

**Comment by kylewm** [comment] 2015-10-23 16:11
The intention is that Bridgy doesn't differentiate -- the url provided via the registration hook should work just fine for all the cases you listed.

I suspect what's happening is you register via the hook, Bridgy gets the custom URL. Then go into Bridgy to add publish support, and at that point it gets the list of URLs fro the silo and wipes out the custom one. If that's the case #522 should help with this!

**Comment by kylewm** [comment] 2015-10-23 16:13
Confirmed with my own account that registering for "publish" wipes out the custom URL

**Comment by singpolyma** [comment] 2015-10-23 16:14
Wait... how do I pass a custom URL?

**Comment by kylewm** [comment] 2015-10-23 16:20
Oh sorry, I didn't realize that was not documented; I will make sure to add this to the FAQ: Pass the query param "user_url" to the registration hook with the custom url

**Comment by singpolyma** [comment] 2015-10-23 16:28
Neat!  If it can "just work" instead of requiring the user to change their social profile, that would be even better than this suggestion for a warning! :)

**Comment by kylewm** [comment] 2015-10-23 16:36
Cool! Apologies for misunderstanding the initial request :) I'll close this when I've updated the FAQ

**Comment by kylewm** [comment] 2015-10-25 01:07
updated about.html in 47fbc87f0c2ba519e06716189bf4d52b47a950f0, thanks again for the heads up!

**Closed by kylewm** 2015-10-25 01:07 UTC
