### ISSUE TITLE
Same bridgy link sent to upstream replies

### ISSUE THREAD

**Issue by gRegorLove** [snarfed/bridgy#455] opened 2015-09-01 02:14 UTC
At first I thought this was silly programmer error on my end (and it still could be :)), but it appears Bridgy sent several webmentions upstream in my notes, but did not include the correct in-reply-to link for the upstream versions, so my processing does not validate them.

Example: I had https://brid-gy.appspot.com/comment/twitter/gRegorLove/638046136603770880/638046281953353728 

sent to three URLs up stream in the thread:

1) http://gregorlove.com/2015/08/indiana_mama-jdragz-ragzdoll13-me-four.we/
2) http://gregorlove.com/2015/08/indiana_mama-jdragz-ragzdoll13-you-have/
3) http://gregorlove.com/2015/08/indiana_mama-yeah-ill-reply-today/

They were all sent within a few seconds of each other. I was manually copying these tweets back to my site, so they were all found in my feed by Bridgy at the same time, if that matters.

Reference:
http://indiewebcamp.com/irc/2015-08-31#t1441071014942 
@snarfed said #217 might be background.

**Comment by snarfed** [comment] 2015-09-01 14:23
thanks for the report! looks like this is indeed a bug somewhere.

**Comment by snarfed** [comment] 2015-09-01 14:28
at first glance, it looks like this is a regression of the behavior described in https://github.com/snarfed/bridgy/issues/217#issuecomment-48930358.

**Comment by snarfed** [comment] 2015-09-01 14:30
oddly, this [Response entity](https://appengine.google.com/datastore/edit?app_id=s~brid-gy&key=aglzfmJyaWQtZ3lyNQsSCFJlc3BvbnNlIid0YWc6dHdpdHRlci5jb20sMjAxMzo2MzgwNDYyODE5NTMzNTM3MjgM)'s `urls_to_activity` property is empty.

**Comment by snarfed** [comment] 2015-09-01 14:32
ugh. i wonder if this is because twitter's search API is best effort only: #202.

**Comment by kylewm** [comment] 2015-09-01 14:56
> oddly, this Response entity's urls_to_activity property is empty.

It's also weird that the activities_json activities don't have any upstreamDuplicates, since clearly original post discovery found those three post URLs to send the webmentions to.

**Comment by kylewm** [comment] 2015-09-01 14:57
I don't *think* it has to do with the search API -- Bridgy's seeing the response to Gregor's post and all of its predecessors in the reply chain.

**Comment by snarfed** [comment] 2015-09-01 15:52
> It's also weird that the activities_json activities don't have any upstreamDuplicates

we actually prune the contents of `activities_json` down to just the bare necessities, to save space: #68
* https://github.com/snarfed/bridgy/blob/master/tasks.py#L284
* https://github.com/snarfed/bridgy/blob/master/util.py#L238

**Comment by snarfed** [comment] 2015-09-01 16:03
@kylewm i think you're right about the search API. i vaguely thought we might use it in the handler to find the previous reply chain again, but no, afaict we pull that from the datastore.

**Comment by snarfed** [comment] 2015-09-01 16:08
odd. the propagate task says [this poll log created the response](https://brid-gy.appspot.com/log?start_time=1440958038&key=aglzfmJyaWQtZ3lyFwsSB1R3aXR0ZXIiCmdSZWdvckxvdmUM), but as far as i can tell, it didn't.

**Comment by snarfed** [comment] 2015-09-01 16:13
hey @gRegorLove do you see this kind of thing regularly? or is this the first time?

**Comment by gRegorLove** [comment] 2015-09-01 17:15
This is the first time. Just recently I've successfully processed upstream webmentions, like my Twitter reply on http://gregorlove.com/2015/08/looking-forward-to-ericagrows-and/

**Comment by snarfed** [comment] 2015-09-01 17:19
thanks! that's what i figured. so this is something unusual and transient. good clue. (and also means we may not prioritize too highly. :smirk:)

**Comment by snarfed** [comment] 2015-09-27 17:05
hey @gRegorLove have you seen this recur at all with any new responses?

**Comment by snarfed** [comment] 2015-10-19 22:11
whatever this was, i suspect it was either fixed or at least changed substantially by #51. tentatively closing. feel free to reopen if you disagree!

**Closed by snarfed** 2015-10-19 22:11 UTC
Labels: listen
