### ISSUE TITLE
Mastodon login and interactive publish broken due to Mastodon/doorkeeper OAuth bug

### ISSUE THREAD

**Issue by troutcolor** [snarfed/bridgy#911] opened 2020-01-19 14:58 UTC
Hi,
I had this working on [my blog](https://johnjohnston.info/blog) posting to mastodon.social using the Syndication Links plugin and then it stopped working.
I not sure if the [bridgy log](https://brid.gy/log?start_time=1578338641&key=agdicmlkLWd5coEBCxINUHVibGlzaGVkUGFnZSJaaHR0cHM6Ly9qb2huam9obnN0b24uaW5mby9ibG9nL2xpc3RlbmVkLW1pY3JvY2FzdC0wODEtYW5hcmNoeS1mZWRlcmF0aW9uLWFuZC10aGUtaW5kaWV3ZWIvDAsSB1B1Ymxpc2gYgIDA27fthAoM) will help or not.

Trying on the bridgy site, I get to this [mastodon page](REDACTED) not sure if that will work?  This says "**We're sorry, but something went wrong on our end**."

Hopefully that makes some sort of sense?
Cheers

john

**Comment by snarfed** [comment] 2020-01-19 20:36
hey, sorry for the trouble! could you try disabling and re-enabling publishing on https://brid.gy/mastodon/@johnjohnston@mastodon.social and see if it works then? i've seen this scope issue with mastodon before, but i'm still trying to track it down.

**Comment by troutcolor** [comment] 2020-01-19 22:20
Hi, thanks. I just tried that and resubmitted a post through the bridgy page. I got the same result. 
Is there any other information I can send that might help?

Cheers
John

**Comment by snarfed** [comment] 2020-01-19 22:45
thanks for trying! that's all i need, i'll investigate.

**Comment by snarfed** [comment] 2020-01-20 00:27
oh god, also, i just noticed the _mastodon page_ link you originally posted included bridgy's client secret for mastodon.social. 😐 i'll reset that. please be careful when posting URLs from login and auth flows! (basically, don't unless you know what you're doing. 😁)

**Comment by troutcolor** [comment] 2020-01-20 17:54
> oh god, also, i just noticed the _mastodon page_ link you originally posted included bridgy's client secret for mastodon.social. 😐 i'll reset that. please be careful when posting URLs from login and auth flows! (basically, don't unless you know what you're doing. 😁)

I certainly don’t know what I am doing. Thanks!

**Comment by snarfed** [comment] 2020-01-21 07:07
i reproduced this tonight and suspect something wrong on mastodon's end: https://github.com/tootsuite/mastodon/issues/12915 . let's see what they say.

**Comment by joebuhlig** [comment] 2020-01-28 16:47
I might have a related issue. I continue to get the yellow pause icon. I can revoke access on Mastodon, log out of Bridgy, and then reinstate everything. But the issue returns. It seems like it's an authorization issue on Mastodon's side, but I can't find any errors to share.

**Comment by snarfed** [comment] 2020-01-28 17:23
oops, sorry @joebuhlig! my fault, looks like an unrelated bug. thanks for the nudge! i think i've fixed it now, mind trying again?

**Comment by joebuhlig** [comment] 2020-01-28 17:50
Just tried the yellow pause button again. It asked for an authorization and then after a couple minutes returned with the pause button again. Do I need to revoke, log out, and start over?

**Comment by snarfed** [comment] 2020-01-28 19:24
no, sorry, my fix needed a bit more to it. deployed that now and tested locally. mind trying again? thanks for your patience!

**Comment by joebuhlig** [comment] 2020-01-28 20:37
Bingo! Thank you much!

**Comment by hs0ucy** [comment] 2020-02-19 15:07
I have the same problem. I tried with the form, then with cURL.

`curl -d 'source=https://hugo.soucy.cc/note/2020/02/lost-connection-to-the-earth.html&target=https://brid.gy/publish/mastodon' \
>   https://brid.gy/publish/webmention
{
  "error":"Couldn't find link to brid.gy/publish/mastodon"`

I disconnected and reconnected but the result is the same.

My mastodon instance is not mastodon.social but mastodon.sdf.org.

Thanks

**Comment by hs0ucy** [comment] 2020-02-19 15:07
I have the same problem. I tried with the form, then with cURL.

`curl -d 'source=https://hugo.soucy.cc/note/2020/02/lost-connection-to-the-earth.html&target=https://brid.gy/publish/mastodon' \
>   https://brid.gy/publish/webmention
{
  "error":"Couldn't find link to brid.gy/publish/mastodon"`

I disconnected and reconnected but the result is the same.

My mastodon instance is not mastodon.social but mastodon.sdf.org.

Thanks

**Comment by hs0ucy** [comment] 2020-02-19 15:15
I revoked bridgy in the mastodon administration panel and re-added it and it's seems to work now.

Thanks.

**Comment by snarfed** [comment] 2020-02-19 15:59
@hs0ucy that looks like a different problem. as the error message says, your post needs to link to https://brid.gy/publish/mastodon . see https://brid.gy/about#webmentions

**Comment by hs0ucy** [comment] 2020-02-19 18:12
> @hs0ucy that looks like a different problem. as the error message says, your post needs to link to https://brid.gy/publish/mastodon . see https://brid.gy/about#webmentions

Oh, you're right ... In my template i had `https://fed.brid.gy` 👎 :/

Thanks!

**Comment by jee-r** [comment] 2020-02-20 11:24
@[GitHub](github.com)

Hello, Is there a cli way to verify if [bridgy](https://brid.gy) is connected to mastodon instance and if is not the case to reconnect it ?

I was thinking something like authorize it with an app <code>https://mastodon.social/settings/applications/new</code>

It’s can be a workaround to avoid unintended disconnection

Thank’s

#bridgy #disconnection #mastodon #cli

(Originally published at: https://jeer.fr/micro/1582197847)

**Comment by snarfed** [comment] 2020-02-20 13:57
@jee-r hmm! are you seeing your bridgy mastodon account get repeatedly disconnected? is that related to the interactive publishing problem here?

**Comment by jee-r** [comment] 2020-02-20 17:38
@snarfed i don't know if it's a real disconnection but sometime when i try to publish i get the error message `out of scope` when it's happened i need to disconnect from bridgy, remove the bridgy's app authorization in mastodon's settings and reconnect again. You are right it's may be more related to https://github.com/snarfed/bridgy/issues/894 than this issue, if it's happened again i'll report rather there.

**Comment by isellsoap** [comment] 2020-07-09 15:08
I have the same exact error since a few weeks now (see a recent [log with the authorization error](https://brid.gy/log?start_time=1594306192&key=agdicmlkLWd5cmQLEg1QdWJsaXNoZWRQYWdlIj1odHRwczovL2ZyYW5jZXNjb3NjaHdhcnouY29tL25vdGVzL21vcmUtaW5mb3MtdG8tZm9sbG93LXNvb24vDAsSB1B1Ymxpc2gYgIDQiM2Z0wkM)). 

The set up should be correct (I think). When trying to send a webmention to Mastodon via Bridgy, the Mastodon Bridgy page shows the pause button ("This account was disconnected on Mastodon's end. Click to reconnect it!"). If I repeat the process after reconnecting the account, the same pattern occurs.

**Comment by snarfed** [comment] 2021-09-02 15:03
I looked at this a bit again recently. Looks like the Mastodon bug is a URL length limit that the OAuth redirect URL hits on their end. It's a bit inconsistent, butt definitely there, across instances. Details in  https://github.com/mastodon/mastodon/issues/12915 😐

**Comment by snarfed** [comment] 2022-08-13 03:17
Discussion is now in https://github.com/doorkeeper-gem/doorkeeper/issues/1554, tentative conclusion is that the issue is in doorkeeper. Still not much more movement though. 😐

**Comment by snarfed** [comment] 2023-01-04 02:45
I'm going to try to work around this by shortening the redirect URL on Bridgy's side.

**Comment by snarfed** [comment] 2023-01-11 04:09
It worked! Specifically snarfed/oauth-dropins@1e987be2449ce491d1c451527a16d6aa5e79b2d9, snarfed/oauth-dropins@0ba0f7100e47647f240101441e7c2daa5b05ca4c. I think we're back in business with Mastodon login and interactive publish.

**Closed** 2023-01-11 04:08 UTC
Labels: publish
