### ISSUE TITLE
Misdirected webmentions from twitter

### ISSUE THREAD

**Issue by peterwilsoncc** [snarfed/bridgy#376] opened 2015-03-14 02:15 UTC
In a conversation, I mentioned and linked to a post on Jeremy Kieth's site, to which I received a reply.

[My mention](https://twitter.com/pwcc/status/576158607114309633) didn't show up on Jeremy's site, but [the reply](https://twitter.com/bobearth/status/576175053974347776) was sent through to both our sites.

I think it relates to allowing for ICYMI reposts.

**Comment by snarfed** [comment] 2015-03-14 03:45
hey peter! so, this is actually the expected behavior. bridgy only sends direct responses to your own posts. it doesn't search all of twitter for mentions of/links to your site. (or in this case, adactio's site, since he's signed up too.) sorry for the confusion!

having said that, this is a fairly complex, subtle issue. we've discussed it pretty thoroughly on #51 and on the wiki, but more feedback is always welcome. feel free to jump in!

tentatively closing...

**Closed** 2015-03-14 03:45 UTC
