### ISSUE TITLE
handle facebook's consolidated "X added n new photos" stories

### ISSUE THREAD

**Issue by beck24** [snarfed/bridgy#562] opened 2015-11-27 06:36 UTC
![screen shot 2015-11-26 at 10 30 44 pm](https://cloud.githubusercontent.com/assets/738363/11435308/efdf244e-948d-11e5-845f-4af0401fd069.png)

The comments from this post is showing up on this post:
http://known.mattbeckett.me/2015/nice-try-non-gmo-project#comments

Not sure if it's a bridgy or known issue.  Will also submit over there.

**Comment by snarfed** [comment] 2015-11-27 09:11
ugh, sorry about that. [our log](https://brid.gy/log?start_time=1448605271&key=aglzfmJyaWQtZ3lyRQsSCFJlc3BvbnNlIjd0YWc6ZmFjZWJvb2suY29tLDIwMTM6MTA3MDI0NTM5OTY3MjU0Nl8xMDcwMjU4OTY2MzM3ODU2DA) shows it's our fault. i'll mention that on the known bug.

i'm tempted to say this is related to #383, figure out how to fix that, and call it a day...but i suspect connecting the comments to the wrong post is a different bug that we should also find. whee!

**Comment by snarfed** [comment] 2015-11-27 09:18
the poll log that created the comments is truncated and doesn't have the useful part. :/

the `SyndicatedPost` entities are correct, they just link the non-GMO known and facebook posts.

here's the propagate log:

```
Params: UnicodeMultiDict([(u'response_key', u'aglzfmJy...')])
Source: Matt Beckett (Facebook) 948590525171368, http://brid-gy.appspot.com/facebook/948590525171368
Created by this poll: http://brid-gy.appspot.com/log?start_time=1448605153&key=aglzfmJyaWQtZ3lyIQsSDEZhY2Vib29rUGFnZSIPOTQ4NTkwNTI1MTcxMzY4DA
Starting Response comment tag:facebook.com,2013:1070245399672546_1070258966337856 https://www.facebook.com/1070245399672546?comment_id=1070258966337856
Webmention from https://brid-gy.appspot.com/comment/facebook/948590525171368/1070373182993101/1070245399672546_1070258966337856 to http://known.mattbeckett.me/2015/a-natural-gmo-now-what
Using cached webmention endpoint u'W http known.mattbeckett.me': http://known.mattbeckett.me/webmention/
Sending...
Starting new HTTP connection (1): known.mattbeckett.me
"POST /webmention/ HTTP/1.1" 202 None
Sent! {'body': u'', 'request': u'POST http://known.mattbeckett.me/webmention/ (with source=https://brid-gy.appspot.com/comment/facebook/948590525171368/1070373182993101/1070245399672546_1070258966337856, target=http://known.mattbeckett.me/2015/a-natural-gmo-now-what)', 'http_status': 202}
Setting last_webmention_sent
Webmention from https://brid-gy.appspot.com/comment/facebook/948590525171368/1070373182993101/1070245399672546_1070258966337856 to http://known.mattbeckett.me/2015/nice-try-non-gmo-project
Using cached webmention endpoint u'W http known.mattbeckett.me': http://known.mattbeckett.me/webmention/
Sending...
Starting new HTTP connection (1): known.mattbeckett.me
"POST /webmention/ HTTP/1.1" 202 None
Sent! {'body': u'', 'request': u'POST http://known.mattbeckett.me/webmention/ (with source=https://brid-gy.appspot.com/comment/facebook/948590525171368/1070373182993101/1070245399672546_1070258966337856, target=http://known.mattbeckett.me/2015/nice-try-non-gmo-project)', 'http_status': 202}
Setting last_webmention_sent
```

looking at the ids in one of the comment handlers, `/comment/facebook/948590525171368/1070373182993101/1070245399672546_1070258966337856`, in order:

* 1070373182993101 is non-GMO photo (ie object) id
* 1070245399672546 is the Edison post id
* 1070258966337856 is "Poor Edison!" comment id

**Comment by snarfed** [comment] 2015-11-27 09:20
hey @beck24, you don't happen to have any other examples of this, do you? totally ok if not, just curious since our logs for this one are incomplete. :/

**Comment by beck24** [comment] 2015-11-27 16:50
I don't, but I'll keep an eye on it.

I'll try to replicate it...  I'll upload a photo with friends only access via mobile, then post a different photo to known with FB syndication and see what happens.
I'm not sure if it will work, but other than the fact that they were both photos and they are adjacent posts in my timeline there really isn't anything connecting them.

**Comment by beck24** [comment] 2015-11-27 17:00
Oh, that reminds me - maybe this is relevant, those posts were 7 hours apart.  I think bridgy had stopped updating things and I went to brid.gy and manually restarted it shortly after posting the non-gmo post.
I imagine that would make replication harder, but maybe it means something to you.

**Comment by beck24** [comment] 2015-11-27 17:31
Interestingly, a comment I made on the Edison post just half an hour ago is still being pushed to the Non-GMO post.  Does that help?

**Comment by beck24** [comment] 2015-11-27 17:54
I've made 2 new posts under the same conditions (same access, same post type, same order) and it's not happening again.  I guess it's due to manually restarting bridgy?
Interesting that new comments posted to the Edison post are still coming through to the Non-GMO post though.

This is the new post I was using as a test, all comments coming in are correctly for that post.  Is it normal that they come in out of order?  I've noticed that with other posts but it didn't bother me enough to mention.  Since I'm here...

http://known.mattbeckett.me/2015/buy-nothing-this-black-friday#comments

**Comment by kylewm** [comment] 2015-11-27 18:03
@snarfed sorry if you already saw this. Bridgy's SyndicatedPost for 

`http://known.mattbeckett.me/2015/nice-try-non-gmo-project` 

links to

`https://www.facebook.com/948590525171368/posts/1070373182993101`

which is one of those "Matt Beckett added 2 new photos." activities and not an actual post permalink.

**Comment by snarfed** [comment] 2015-11-27 18:18
ah, thanks! the new comment is definitely useful. and, i don't think restarting your account caused it, but I'll definitely keep it in mind.

ordering is a tough one, since Facebook doesn't actually tell us when each comment was made, and there are a bunch of async queues along the way in bridgy and known... but us bridgy preserves order, that might do it. I'll look into that. thanks for the nudge!

**Comment by beck24** [comment] 2015-11-27 18:34
Oooh ooh - replication!

http://known.mattbeckett.me/2015/buy-nothing-this-black-friday#comments

Comments from the test post are actually coming through.  
![screen shot 2015-11-27 at 10 33 26 am](https://cloud.githubusercontent.com/assets/738363/11446862/55185330-94f2-11e5-91f2-fc05c21f42f5.png)

^ These comments should actually belong to this post
https://www.facebook.com/matt.beckett.39/posts/1070590272971392

**Comment by snarfed** [comment] 2015-11-27 21:52
augh facebook fml :sob: :gun: 

thank you @kylewm for double checking the `SyndicatedPost`s! i only lightly glanced at the ids; glad you looked closer.

@beck24 the problem is that when you post multiple pictures in a certain amount of time, facebook may collapse them into a single "X added n new photos" timeline story, sometimes retroactively to one of the individual posts with the same id.

@kylewm do you remember if we've ever done a deep dive into this or found FB developer-oriented docs on it?

**Comment by snarfed** [comment] 2015-11-27 23:17
btw i was wrong about comment ordering, looks like we get FB comment timestamps and send them to known properly. i filed a bug with them, attached above.

**Comment by armingrewe** [comment] 2015-11-27 23:24
@snarfed this "facebook may collapse them into a single "X added n new photos" timeline story" doesn't only happen with pictures. I've seen it happen with Tumblr posts (I have my Tumblr posts feeding to Twitter and FB) and I think also with Vine videos, but I'm not entirely sure about the latter. I haven't really spotted any rhyme or rhythm in it though, sometimes it happens, sometimes it doesn't...

**Comment by rpannek** [comment] 2015-11-30 21:58
I have the same problem with a couple of comments like:

https://brid-gy.appspot.com/comment/facebook/728407677/10154334939807678/10154331930037678_10154345865592678
https://brid-gy.appspot.com/comment/facebook/728407677/10154334939807678/10154331930037678_10154332303892678
https://brid-gy.appspot.com/comment/facebook/728407677/10154334939807678/10154331930037678_10154342491442678

**Comment by snarfed** [comment] 2015-12-06 16:25
aha. the account wasn't actully deleted, he just changed his username: https://twitter.com/rossini_martins ...which we actually handled fine, even including searching for replies with @rossini_martins.

ok. one mystery solved. still need to fine tune our twitter search for links though.

**Comment by kylewm** [comment] 2015-12-06 23:30
Trying to sort basically this same thing out with silo.pub... I just uploaded a photo and got the return value

**Comment by kylewm** [comment] 2015-12-06 23:36
oh damn, OK. so actually what happened is I uploaded the first photo, got back

``
{
  'id': 'XXXX'
  'post_id': 'USERID_XXXX'
}
```

then uploaded the second photo and got back

``
{
  'id': 'YYYY'
  'post_id': 'USERID_XXXX'
}
```

XXXX -- the first photo's ostensible ID -- *became* the collapsed n-new photos post. Apparently I was never given an ID that uniquely identifies the first photo.

**Comment by snarfed** [comment] 2015-12-06 23:54
thanks for investigating!

yeah, that's the behavior i've seen before too. photos each have a unique photo object (`id` here, `object_id` from the API) and a not necessarily unique post object (`post_id` here, `id ` from the API). when more picture(s) are posted within the time limit, the post object turns into a consolidated post and continues to accumulate any more photos uploaded within the limit. (and maybe the limit gets extended, not sure.)

it's _great_ that we have this explicitly tested now. it'd probably worth documenting what we know on https://indiewebcamp.com/Facebook or wherever. and maybe the fix is as simple as no longer [assuming a one to one mapping between photo objects and story objects?](https://github.com/snarfed/granary/blob/master/granary/facebook.py#L352)

**Comment by snarfed** [comment] 2015-12-07 03:20
the next step here is to check how comments behave. i think the photo objects only get their own comments, and the post objects get copies of all the photos' comments...but i'm not sure.

**Comment by snarfed** [comment] 2015-12-07 03:21
...and likes and shares too, i guess.

**Comment by snarfed** [comment] 2015-12-09 17:36
hey @kylewm, since you've got that consolidated post set up, would you mind doing a little more investigation? specifically, mind commenting on each object - the consolidated post and the two photos - and then fetch the objects from the API with their ids and post the JSON here? or send it to me offline if you prefer. i'd do it myself, but https://www.facebook.com/will.a.bharambesen 404s, maybe since his profile is private? :P

**Comment by kylewm** [comment] 2015-12-09 18:14
(he's a silo.pub Test User)

I tried commenting on the two photos and the album

Fetching the consolidated post ID:

/v2.5/111018509268924_111054749265300

```json
{
  "created_time": "2015-12-06T21:18:47+0000",
  "story": "Will Alajhbcbegggc Bharambesen added 4 new photos.",
  "id": "111018509268924_111054749265300"
}
```

Fetch comments for the consolidated ID -- gives the comment on the first photo only!

/v2.5/111018509268924_111054749265300?fields=comments
and
/v2.5/111018509268924_111054749265300/comments

```json
{
  "comments": {
    "data": [
      {
        "from": {
          "name": "Will Alajhbcbegggc Bharambesen",
          "id": "111018509268924"
        },
        "message": "A comment on the first single photo",
        "created_time": "2015-12-09T18:01:25+0000",
        "id": "111054749265300_114701712233937"
      }
    ],
    "paging": {
      "cursors": {
        "after": "WTI5dGJXVnVkRjlqZFhKemIzSTZNVEUwTnpBeE56RXlNak16T1RNM09qRTBORGsyT0RRd09EWT0=",
        "before": "WTI5dGJXVnVkRjlqZFhKemIzSTZNVEUwTnpBeE56RXlNak16T1RNM09qRTBORGsyT0RRd09EWT0="
      }
    }
  },
  "id": "111018509268924_111054749265300"
}
```

Comment on the second picture solo 

/v2.5/111117232592385?fields=comments
and 
/v2.5/111018509268924_111117232592385?fields=comments
and
/v2.5/111018509268924_111117232592385/comments

```json
{
  "comments": {
    "data": [
      {
        "created_time": "2015-12-09T18:01:48+0000",
        "from": {
          "name": "Will Alajhbcbegggc Bharambesen",
          "id": "111018509268924"
        },
        "message": "a comment on the second photo",
        "id": "111117232592385_114705138900261"
      }
    ],
    "paging": {
      "cursors": {
        "before": "WTI5dGJXVnVkRjlqZAFhKemIzSTZANVEUwTnpBMU1UTTRPVEF3TWpZAeE9qRTBORGsyT0RReE1EZAz0ZD",
        "after": "WTI5dGJXVnVkRjlqZAFhKemIzSTZANVEUwTnpBMU1UTTRPVEF3TWpZAeE9qRTBORGsyT0RReE1EZAz0ZD"
      }
    }
  },
  "id": "111117232592385"
}
```

I don't have the right permissions for silo.pub to try fetching /me/album to get the ID of the actual album  (called "silo.pub Photos", and distinct from the consolidated 4-new-photos post)

**Comment by snarfed** [comment] 2015-12-09 20:00
thanks @kylewm!

i also looked at matt's photo and consolidated post objects with v2.2. interestingly, `/v2.2/948590525171368_1070373182993101` (id USERID_POSTID) returns the consolidated post, while just `/v2.2/1070373182993101` (same POSTID!) returns an individual photo object. facebook you so crazy!

useful: the consolidated post object has `object_id`, `type=photo`, and especially `status_type=added_photos`.

```json
/v2.2/948590525171368_1070373182993101

{
  "id": "948590525171368_1070373182993101"
  "object_id": "1070591592971260",
  "status_type": "added_photos",
  "type": "photo",
  "link": "https://www.facebook.com/photo.php?fbid=1070591592971260&set=a.948627845167636.1073741831.100000612876186&type=3",
  "story": "Matt Beckett added 2 new photos to the album: known.mattbeckett.me Photos.",
  "name": "known.mattbeckett.me Photos",
  "picture": "https://scontent.xx.fbcdn.net/hphotos-xft1/v/t1.0-0/s130x130/12316348_1070591592971260_4173282704167778273_n.jpg?oh=dfe2ca11067d234ca2def60c8b8dfae1&oe=56D688A0",
  "from": {
    "name": "Matt Beckett",
    "id": "948590525171368"
  },
  "application": {"name": "known.mattbeckett.me", "id": "860763080638367"},
}
```

```json
/v2.2/1070591592971260

{
  "id": "1070591592971260",
  "link": "https://www.facebook.com/photo.php?fbid=1070591592971260&set=a.948627845167636.1073741831.100000612876186&type=3",
  "name": "Buy nothing this Black Friday ...",
  "from": {
    "name": "Matt Beckett",
    "id": "948590525171368"
  },
  "images": [...],
  "comments": {...},
  "likes": {...},
  "picture": "https://scontent.xx.fbcdn.net/hphotos-xft1/v/t1.0-0/s130x130/12316348_1070591592971260_4173282704167778273_n.jpg?oh=dfe2ca11067d234ca2def60c8b8dfae1&oe=56D688A0",
  "source": "https://scontent.xx.fbcdn.net/hphotos-xft1/t31.0-8/s720x720/12265926_1070591592971260_4173282704167778273_o.jpg",
}
```

**Comment by snarfed** [comment] 2015-12-09 20:00
thanks @kylewm!

i also looked at matt's photo and consolidated post objects with v2.2. interestingly, `/v2.2/948590525171368_1070373182993101` (id USERID_POSTID) returns the consolidated post, while just `/v2.2/1070373182993101` (same POSTID!) returns an individual photo object. facebook you so crazy!

useful: the consolidated post object has `object_id`, `type=photo`, and especially `status_type=added_photos`.

```json
/v2.2/948590525171368_1070373182993101

{
  "id": "948590525171368_1070373182993101"
  "object_id": "1070591592971260",
  "status_type": "added_photos",
  "type": "photo",
  "link": "https://www.facebook.com/photo.php?fbid=1070591592971260&set=a.948627845167636.1073741831.100000612876186&type=3",
  "story": "Matt Beckett added 2 new photos to the album: known.mattbeckett.me Photos.",
  "name": "known.mattbeckett.me Photos",
  "picture": "https://scontent.xx.fbcdn.net/hphotos-xft1/v/t1.0-0/s130x130/12316348_1070591592971260_4173282704167778273_n.jpg?oh=dfe2ca11067d234ca2def60c8b8dfae1&oe=56D688A0",
  "from": {
    "name": "Matt Beckett",
    "id": "948590525171368"
  },
  "application": {"name": "known.mattbeckett.me", "id": "860763080638367"},
}
```

```json
/v2.2/1070591592971260

{
  "id": "1070591592971260",
  "link": "https://www.facebook.com/photo.php?fbid=1070591592971260&set=a.948627845167636.1073741831.100000612876186&type=3",
  "name": "Buy nothing this Black Friday ...",
  "from": {
    "name": "Matt Beckett",
    "id": "948590525171368"
  },
  "images": [...],
  "comments": {...},
  "likes": {...},
  "picture": "https://scontent.xx.fbcdn.net/hphotos-xft1/v/t1.0-0/s130x130/12316348_1070591592971260_4173282704167778273_n.jpg?oh=dfe2ca11067d234ca2def60c8b8dfae1&oe=56D688A0",
  "source": "https://scontent.xx.fbcdn.net/hphotos-xft1/t31.0-8/s720x720/12265926_1070591592971260_4173282704167778273_o.jpg",
}
```

**Comment by snarfed** [comment] 2015-12-09 22:18
same pattern with [this consolidated post](https://www.facebook.com/1407574399567467/posts/1520022328322673) from test user (ahem) Snoøpy Barrett. `/v2.2/1407574399567467_1520022328322673` returns the consolidated post, which includes `object_id`, `type=photo`, and `status_type=added_photos`. `/v2.2/1520022328322673` returns the first photo object.

**Comment by snarfed** [comment] 2015-12-09 22:54
here's a non-consolidated post. sadly it looks almost the same as the consolidated one. in particular, it has `object_id`, `type=photo`, and `status_type=added_photos` too.

```json
/v2.2/212038_10102004709308273

{
  "id": "212038_10102004709308273"
  "object_id": "10102004709273343",
  "status_type": "added_photos",
  "type": "photo",
  "link": "https://www.facebook.com/photo.php?fbid=10102004709273343&set=a.725223993143.2289690.212038&type=3",
  "story": "Ryan Barrett with Gina Rossman Barrett.",
  "message": "sippin on some syrup",
  "picture": "https://scontent.xx.fbcdn.net/hphotos-xfp1/v/t1.0-0/s130x130/12341573_10102004709273343_4308588042540558292_n.jpg?oh=0dd6126e12b83de3516217f77d3bf513&oe=572219AB",
  "from": {
    "name": "Ryan Barrett",
    "id": "212038"
  },
  "comments": {...}
  "likes": {...}
}
```

**Comment by snarfed** [comment] 2015-12-09 23:19
confirmed. [here's a non-consolidated post](https://www.facebook.com/photo.php?fbid=10101921412066613&set=a.725223993143.2289690.212038&type=3&theater) with no `message`.

...which may mean there's no structural way to tell consolidated and non-consolidated posts apart. you either parse the story field, with all the brittleness that entails, or you switch to only handling photo objects via `object_id`, and ignore the post objects altogether. hrmph.

```json
/v2.2/212038_10101921412066613

{
  "id": "212038_10101921412066613"
  "object_id": "10101921412066613",
  "type": "photo",
  "status_type": "added_photos",
  "story": "Ryan Barrett added a new photo — at Pop-Up Magazine.",
  "name": "Mobile Uploads",
  "from": {
    "name": "Ryan Barrett",
    "id": "212038"
  },
  "link": "https://www.facebook.com/photo.php?fbid=10101921412066613&set=a.725223993143.2289690.212038&type=3",
  "picture": "https://scontent.xx.fbcdn.net/hphotos-xtl1/v/t1.0-0/s130x130/12106739_10101921412066613_1859979090960798014_n.jpg?oh=876d23c1a1c876017a8f5fd1eaf87654&oe=56E66072",
  "place": {"..."},
}
```

**Comment by snarfed** [comment] 2015-12-10 21:21
current plan is to always replace post objects with photo objects without merging any data from the post objects.

the catch is that i need to figure out public vs private: https://github.com/snarfed/bridgy/issues/383#issuecomment-90935938 . the `privacy` field is only in the post object, but it looks like it's always `CUSTOM` in consolidated posts, even when all of the consolidated photos are public...so then we have to fetch the...album?...and look at its `privacy` field? not sure. gah. fml.

**Comment by beck24** [comment] 2015-12-10 21:23
That sounds terribly complicated.  Sorry :(

**Comment by snarfed** [comment] 2015-12-10 21:38
yup. that looks right, based on looking at these examples in the explorer and docs. the catches are:
* photo objects don't include the `album` field by default, so we'll have to ask for it explicitly with `?fields=album`, which means we *also* have to ask for all of the other fields we want.
* the [`Album.privacy` field](https://developers.facebook.com/docs/graph-api/reference/v2.2/album/#readfields) is a different type and format (single string) than the [`Post.privacy` field](https://developers.facebook.com/docs/graph-api/reference/v2.2/post#fields) (composite object).

gah fml indeed.

**Comment by snarfed** [comment] 2015-12-11 03:48
on the plus side, if consolidated posts all have privacy `CUSTOM`, that's at least a way to distinguish them. small favors!

**Comment by snarfed** [comment] 2015-12-12 16:18
deployed this just now and it looks ok. tentatively closing. woo!

**Closed by snarfed** 2015-12-12 16:18 UTC
Labels: listen, now

**Comment by beck24** [comment] 2015-12-12 22:03
Fantastic, thank you!
