### ISSUE TITLE
misleading error message when no valid mf2-object is found

### ISSUE THREAD

**Issue by sknebel** [snarfed/bridgy#735] opened 2017-03-24 18:23 UTC
Today we had someone on the search for debugging help in #indieweb: https://chat.indieweb.org/2017-03-24#t1490365149749000

They got an error message of `Could not find content in h-entry or any other element!`, when they had an `h-as-article` class on a tag around the `h-entry`.

If I have mentally executed the loop at https://github.com/snarfed/bridgy/blob/master/publish.py#L255 correctly, this unknown type lead to the loop being aborted in L261, so that types is still empty after the loop, which leads to a misleading error message in https://github.com/snarfed/bridgy/blob/master/publish.py#L292

I would have expected an error message that either lists all found top-level types, together with a message that they are not understood, or an error reporting that no h-item was found.

**Comment by snarfed** [comment] 2017-07-13 16:11
thanks again for filing! finally made it back to this.

the original post http://benclark.studio/testing-brid-gy/ is gone, sadly, but i've reproduced his setup locally, twenty seventeen theme and the content he gave in IRC - `<div class="h-entry"><p class="e-content"> Testing brid.gy for backfeed syndication and crossposting </p></div> ...` - and i can't reproduce the `Could not find content in h-entry or any other element!` error. i've also tried with twenty fifteen and sempress, and the uf2 plugin both on and off, but no luck. they all work.

afaik `h-as-article` is a red herring. neither bridgy publish nor mf2 notice or care about `h-as-*` classes. (you can confirm with github searches for `'as'`, `-as`, `as-`.)

the good news is, bridgy actually already does what you suggested: it reports unknown top level type(s) if it can't find anything else publish. the error message here is slightly different, though: it understood the types it saw, but it didn't find any _content_ to publish.

having said that, you're definitely right that the error messages for bad mf2 aren't ideal. accurately diagnosing and describing all possible mf2 problems would be a huge challenge, and i don't plan to tackle it in bridgy publish. [i lean on the docs instead.](https://brid.gy/about#microformats) i'm definitely open to other error message ideas though!

**Comment by sknebel** [comment] 2017-07-13 16:53
To clarify the issue as I remember it: The mf2 parser *does* care about `h-as-article` - it turns it into a microformats object. Taking assumed page HTML
```html
<div class="h-as-entry">
<div class="h-entry">
<p class="e-content">I'M CONTENT</p>
</div></div>
```
this parses as 
```json
 "items": [
        {
            "type": [ "h-as-entry"],
            "properties": {
                "name": ["I'M CONTENT"]
            },
            "children": [
                {
                    "type": [ "h-entry"],
                    "properties": {
                        "content": [
                            {
                                "html": "I'M CONTENT",
                                "value": "I'M CONTENT"
                            }
                        ], … 
```

in that structure, brid.gy never finds the `h-entry`, since it starts at the `h-as-entry` and doesn't look at its children. `Could not find content in h-entry or any other element!` as error kind of sounds like that it found the `h-entry`, but that didn't have content, and the problematic type of `h-as-entry` does not appear at all. An error like `Could not find top-level h-entry (saw ['h-as-entry']` would make it clear that it did not fail on some problem with the `h-entry`, but never found it in the first place due to being nested.

**Comment by snarfed** [comment] 2017-07-13 17:08
aha, true! i misunderstood your original report to mean the tag was `<div class="h-as-article h-entry">`. you're absolutely right, if it's `<div class="h-as-..."><div class="h-entry">`, bridgy sees that `h-as-...` isn't in its [list of known mf2 types](https://github.com/snarfed/bridgy/blob/8bcbdcd2bd9f1321c5d5bcc3c9f5a1c05aa4680c/publish.py#L64), and it's conservative and doesn't try to publish it _or_ look at its children.

i'm honestly not sure what to do here. i'm reluctant to add too much smarts to bridgy's mf2 handling, since mf2 can come in arbitrarily complicated shapes, and due to https://snarfed.org/2015-11-29_keep-bridgy-publish-dumb ...but i don't know. cc @tantek @aaronpk @kevinmarks, any of you have advice?

**Comment by sknebel** [comment] 2017-07-13 17:28
After reading the code more thoroughly, there already is an error message like this
```python
      if types:
        msg = ("%s doesn't support type(s) %s, or no content was found." %
               (source_cls.GR_CLASS.NAME, ' + '.join(types)))
```

and the `types` variable just is not filled in this specific case. This change might fix it https://github.com/snarfed/bridgy/compare/master...sknebel:patch-1 , or am I missing a side effect of that?

**Comment by snarfed** [comment] 2017-07-13 17:36
glad you're diving in! thank you! yes, that patch would indeed switch to this error message, which is a good step. mind adding a test and filing a PR? i'd happily merge then! https://github.com/snarfed/bridgy/blob/8bcbdcd2bd9f1321c5d5bcc3c9f5a1c05aa4680c/test/test_publish.py#L1144 is probably a good template.

i still wonder if we should also start examining the children of unknown types...but still not sure.

**Comment by sknebel** [comment] 2017-07-13 17:42
Ok, I'll work on a PR!

I don't think looking into the children of unknown types would be a good idea - it's good to catch and correct these things early, otherwise every single piece of the ecosystem will have to be as lenient, and it sounds like a potential source of evil bugs (really don't want to accidentally tweet someones comment on my post for example ;))

**Comment by snarfed** [comment] 2017-07-13 17:45
fair point, makes sense.

btw if you want to be lazy, you don't have to set up build and run everything tests locally. you can just add the test and file the PR, and [CircleCI should run the tests automatically](https://circleci.com/gh/snarfed/bridgy) and report results there.

**Comment by snarfed** [comment] 2017-07-25 01:15
@sknebel i merged your patch and added a test. hope you don't mind. thanks again!

**Closed by snarfed** 2017-07-25 01:15 UTC
