### ISSUE TITLE
Facebook extension flaky?

### ISSUE THREAD

**Issue by nekr0z** [snarfed/bridgy#1036] opened 2021-05-19 18:41 UTC
After initial set up. the extension found some posts and replies, and even tried to backfeed them. However, ever since that initial success I seem to be having an issue. Extension seems to discover new posts and replies (judging by increasing counters), and it thinks that it is connected to Bridgy properly, but it looks like Bridgy doesn't receive those replies and reactions.

Tested on Firefox and Chrome.

**Comment by snarfed** [comment] 2021-05-19 22:53
Hmm, sorry for the trouble! Will look.

**Comment by snarfed** [comment] 2021-05-21 13:55
Would you mind sending me the JS console logs from the extension? Here's how to get them, in Firefox.

1. Open `about:debugging`
2. Click _This Firefox_ on the left
3. Scroll down to Bridgy
4. Click _Inspect_ <img width="998" alt="image" src="https://user-images.githubusercontent.com/778068/119147612-9c4d2580-ba00-11eb-8d91-39487a662288.png">
5. Click on the _Console_ tab
6. Right click, _Export Visible Messages To_, _File_, save the file. <img width="391" alt="image" src="https://user-images.githubusercontent.com/778068/119147959-e6360b80-ba00-11eb-8e35-647850177f4c.png">
7. Email the file to bridgy@ryanb.org. (Don't post here because it has tokens and cookies.)

**Comment by nekr0z** [comment] 2021-05-21 15:04
Done.

You'll notice Instagram complains; that's because I don't have an Instagram account. Also, it claims to have detected Firefox Container add-on, but I actually only have 5 extensions installed (7 if you count the language pack and the default theme), and Container add-on is not one of them.

**Comment by snarfed** [comment] 2021-05-26 13:51
Found a lead here. Bridgy thinks your recent posts are all non-public, even though they're public:

```
"Found 8 private activities: dict_keys(['tag:facebook.com,2013:10156100220807085', 'tag:facebook.com,2013:10157083594497085', 'tag:facebook.com,2013:10157683310947085', 'tag:facebook.com,2013:10157739093107085', 'tag:facebook.com,2013:10157807120592085', 'tag:facebook.com,2013:10156081386727085', 'tag:facebook.com,2013:10156071353967085', 'tag:facebook.com,2013:10156067899237085'])" 
```

Even Facebook's API makes notoriously complicated and difficult to tell when a post is public or not, so I'm not surprised that Bridgy's scraping is having trouble too. I'll look though!

**Comment by snarfed** [comment] 2021-05-27 04:57
Figured out the problem here. mbasic.facebook.com has very few landmarks in the HTML to grab for scraping, most ids and classes are compiled strings like `do` and `u_0_0_7W`, so I look for English words in the UI in a few places. Your language in Facebook is set to Russian, so those don't work.

I'll see what I can do.

**Comment by nekr0z** [comment] 2021-05-27 06:52
Wow! If you fail to work around this, it's worth documenting, I think.

Meanwhile, switching Facebook interface to English made everything work, except for two mentions:
* https://brid.gy/log?start_time=1622098121&key=agdicmlkLWd5clkLEghSZXNwb25zZSJLdGFnOmZhY2Vib29rLmNvbSwyMDEzOjEwMTU2MTAwMjIwODA3MDg1X9C90YDQsNCy0LjRgtGB0Y9fYnlfMTAwMDA2ODU0MTA2MjA4DA
* https://brid.gy/log?start_time=1622098126&key=agdicmlkLWd5ckcLEghSZXNwb25zZSI5dGFnOmZhY2Vib29rLmNvbSwyMDEzOjEwMTU3ODA3MTIwNTkyMDg1XzEwMTU3ODA5MDYwNjg3MDg1DA

Do you think these are separate issues, or part of this one?

**Comment by snarfed** [comment] 2021-05-28 05:27
Looks like those two eventually finished after retrying. And I've added Russian language support for public vs private. Obviously isn't scalable or sustainable, but scraping itself isn't scalable or sustainable, so 🤷.

Thanks again for filing!

**Comment by nekr0z** [comment] 2021-05-28 11:10
> Looks like those two eventually finished after retrying.

Nope, not really, the logs hang on "Starting Response" and the webmentions haven't been sent:

https://brid.gy/log?start_time=1622181327&key=agdicmlkLWd5clkLEghSZXNwb25zZSJLdGFnOmZhY2Vib29rLmNvbSwyMDEzOjEwMTU2MTAwMjIwODA3MDg1X9C90YDQsNCy0LjRgtGB0Y9fYnlfMTAwMDA2ODU0MTA2MjA4DA

https://brid.gy/log?start_time=1622181334&key=agdicmlkLWd5ckcLEghSZXNwb25zZSI5dGFnOmZhY2Vib29rLmNvbSwyMDEzOjEwMTU3ODA3MTIwNTkyMDg1XzEwMTU3ODA5MDYwNjg3MDg1DA

**Comment by snarfed** [comment] 2021-05-28 13:49
Ah, sorry, got it. I thought they were failed, but they actually just never found the original post URL. Got it, will look.

**Comment by nekr0z** [comment] 2021-06-20 09:46
I noticed that a lot of times it would try to send and seemingly succeed: https://brid.gy/log?start_time=1624182312&key=agdicmlkLWd5ckcLEghSZXNwb25zZSI5dGFnOmZhY2Vib29rLmNvbSwyMDEzOjEwMTU3ODA3MTIwNTkyMDg1XzEwMTU3ODA5MDYwNjg3MDg1DA

But it's actually sending a webmention from a 404 page: https://brid.gy/comment/facebook/722007084/10157807120592085/10157807120592085_10157809060687085

**Comment by snarfed** [comment] 2021-06-20 16:58
Thanks for following up! This was a great lead, helped me find and fix a bug. I think this one has now gone through. Feel free to retry others too!

**Comment by nekr0z** [comment] 2021-06-20 17:19
Awesome!

One more catch: looks like the links themselves for the likes differ depending on the language selected. [This one](https://brid.gy/log?start_time=1624208961&key=agdicmlkLWd5clkLEghSZXNwb25zZSJLdGFnOmZhY2Vib29rLmNvbSwyMDEzOjEwMTU3ODc2NDE2MzY3MDg1X9C90YDQsNCy0LjRgtGB0Y9fYnlfMTAwMDA1NzE4OTkwODM2DA) was caught by brid.gy when the language was set to Russian, and now that it's set to English it 404s, since the word "liked" in the URL got translated.

I also see several stuck on "Starting Response"; like [this one](https://brid.gy/log?start_time=1624208958&key=agdicmlkLWd5clILEghSZXNwb25zZSJEdGFnOmZhY2Vib29rLmNvbSwyMDEzOjEwMTU3ODc2NDE2MzY3MDg1X2xpa2VkX2J5X2FuYXN0YXNpYXBvZGtvbHppbmEM).

**Comment by snarfed** [comment] 2021-06-23 03:14
Thanks again for the detailed reports!

> I also see several stuck on "Starting Response"; like [this one](https://brid.gy/log?start_time=1624208958&key=agdicmlkLWd5clILEghSZXNwb25zZSJEdGFnOmZhY2Vib29rLmNvbSwyMDEzOjEwMTU3ODc2NDE2MzY3MDg1X2xpa2VkX2J5X2FuYXN0YXNpYXBvZGtvbHppbmEM).

Looks like this one is because we don't currently discover original links from link attachments like in this post, https://www.facebook.com/story.php?story_fbid=10157876416367085&id=722007084. I'll work on that.

**Comment by snarfed** [comment] 2021-06-23 03:28
> One more catch: looks like the links themselves for the likes differ depending on the language selected. [This one](https://brid.gy/log?start_time=1624208961&key=agdicmlkLWd5clkLEghSZXNwb25zZSJLdGFnOmZhY2Vib29rLmNvbSwyMDEzOjEwMTU3ODc2NDE2MzY3MDg1X9C90YDQsNCy0LjRgtGB0Y9fYnlfMTAwMDA1NzE4OTkwODM2DA) was caught by brid.gy when the language was set to Russian, and now that it's set to English it 404s, since the word "liked" in the URL got translated.

True! Confirmed, this one is now in Bridgy's database with source URL https://brid.gy/like/facebook/722007084/10157876416367085/100005718990836. Apologies, I'm probably not going to try to backfill the mismatched responses in that window, but feel free to send them yourself by translating the source URLs like this one. https://brid.gy/about#source-urls

**Comment by nekr0z** [comment] 2021-06-23 05:01
> Looks like this one is because we don't currently discover original links from link attachments like in this post,

Shouldn't the fact that the Facebook publication is linked to in the original post have done the trick anyway?

**Comment by snarfed** [comment] 2021-06-23 05:17
Yes! It definitely shouldn have. Thanks for the nudge, I'll look at that too.

**Comment by snarfed** [comment] 2021-06-23 06:16
Ok, I think the bugs here are fixed. Thank you again for your patience, this was really helpful!

Some of the previous responses have been backfilled, but probably not all. The bugs should be fixed going forward though.

Tentatively closing, but feel free to reopen.

**Closed by snarfed** 2021-06-23 06:16 UTC

**Comment by nekr0z** [comment] 2021-06-23 07:17
Something's not right: https://brid.gy/log?start_time=1624432564&key=agdicmlkLWd5ck4LEghSZXNwb25zZSJAdGFnOmZhY2Vib29rLmNvbSwyMDEzOjEwMTU3ODc2NDE2MzY3MDg1X2xpa2VkX2J5XzEwMDAwNTcxODk5MDgzNgw

**Comment by snarfed** [comment] 2021-06-23 14:33
Ah, 500 from webmention.io? It was down a bit yesterday, I think out of disk, so this might have been related. I tried this one again and webmention.io accepted it ok this time.

**Comment by nekr0z** [comment] 2021-06-23 18:21
So those python traces are from that side? Nevermind then ;-)
