### ISSUE TITLE
publish should propagate person-tags to POSSE copies

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#459] opened 2015-09-05 14:18 UTC
When you use Bridgy Publish to POSSE a photo post, it should read the person-tags from the original post, and propagate them to the POSSE copy (e.g. to Facebook or Twitter).

Original question/request: http://indiewebcamp.com/irc/2015-09-01/line/1441139069479

See also:
http://indiewebcamp.com/person-tag

This could be implemented in at least a couple of steps/iterations.

Phase 1: only use person-tag URLs of silo profiles that are directly indicated in the h-cards of the person-tags on the original photo post. E.g. a person-tag h-card could have multiple u-urls on it, and if one of them happens to match the silo domain, use it as the identity to person-tag on the POSSE post! (I'll add an example of how a person-tag publisher could do this to the indiewebcamp wiki to hopefully make it more concrete).

Phase 2: look up the person-tag's silo profile equivalent via rel=me identity lookup on their website. This would require Bridgy to retrieve the first u-url of the person-tag h-card, parse it for rel=me links (i.e. use a microformat2 parser), use the first one of those rel=me links that happens to match the silo domain as the identity to person-tag on the POSSE post! This could require Bridgy to do one additional HTTP(S) request per person-tag on a post which thus depends on the number of people in a photo.

**Comment by snarfed** [comment] 2015-09-05 15:09
thanks for all the details! agreed, this would definitely be fun to have.

**Comment by snarfed** [comment] 2015-09-05 15:10
updated title since we should ideally do this for all silo person tags, not just on posts published by bridgy.

**Comment by snarfed** [comment] 2015-09-05 15:11
oh wait sorry, i misread. this is the other direction. reverting that change.

**Comment by snarfed** [comment] 2015-09-05 15:13
slightly modified since afaik it's not technically photo-specific: you can person-tag arbitrary FB/twitter posts, with or without a photo.

**Comment by tantek** [comment] 2015-09-05 15:44
agreed, more than just photos, photos just happen to be key (driving) use-case :) 

Also, extended person-tag markup example added as promised: http://indiewebcamp.com/person-tag#With_other_profiles

Inline for your convenience:
```
<span class="u-category h-card"> 
  <a class="u-url p-name" href="http://ben.thatmustbe.me/">Ben Roberts</a> 
  (<a class="u-url" href="https://twitter.com/dissolve333">t</a>, 
   <a class="u-url" href="https://www.facebook.com/dissolve333">f</a>)
</span> 
```

**Comment by snarfed** [comment] 2015-09-17 23:46
turns out this a dupe of #318, but it has useful details, so i'm closing #318 instead.

**Comment by tantek** [comment] 2015-09-24 16:32
And on the backfeed side: #488

**Comment by snarfed** [comment] 2015-11-05 23:31
current silo support:

* Twitter: no. they're called [photo or people tags](https://support.twitter.com/articles/20156423#). nothing in the [uploading media](https://dev.twitter.com/rest/public/uploading-media) or [`statuses/update`](https://dev.twitter.com/rest/reference/post/statuses/update) docs, [doc searches](https://dev.twitter.com/search/node/photo%20tags%20language%3Aen), or forum [searches](https://twittercommunity.com/search?q=tags%20category%3A20) or [posts](https://twittercommunity.com/t/tag-users-on-pictures/54766).
* Facebook: TODO
* Instagram: no, since the API is mostly read only. you [can't post pictures](https://instagram.com/developer/endpoints/media/) [or tags](https://instagram.com/developer/endpoints/tags/).
* Google+: no, since [the API is read only](https://developers.google.com/+/web/api/rest/index#api).

**Comment by snarfed** [comment] 2015-11-16 01:09
facebook is done! tested just now and it works. [silo SWAT0](https://indiewebcamp.com/SWAT0) here we come!

**Comment by snarfed** [comment] 2015-11-17 20:30
flick is done now too, thanks @kylewm!

tentatively closing this since the other three silos aren't possible. if anyone badly wants this for the other silos and really wants to track it in case they add support in the future, feel free to reopen.

**Comment by tantek** [comment] 2016-01-19 16:59
Looks like this may have broken recently in Bridgy Publish photos + person-tags to Flickr at least.

This post: http://tantek.com/2016/018/t4/w3cab-meeting-hawaii (has a bunch of person-tags)
Bridgy Publish POSSE to Facebook copy: https://www.facebook.com/photo.php?fbid=10102083967065093

Note that *none* of the person-tags (including my tagging myself) made it to the POSSE copy on Facebook.

All of the person-tags on that post (including of me) were added afterwards by Coralie (as you can see by hovering over the person-tags and looking the top left of the resulting pop-up where it says in small white text "Tagged by Coralie Mercier".

Any idea what broke? Re-open this?

**Comment by kylewm** [comment] 2016-01-19 17:33
For reference, we originally noticed that person tags seemed to work when you use the person's numeric ID as their URL in http://tantek.com/2015/350/t2/seasons-greetings-homebrew-website-club where it successfully tagged Marc Canter, even though he has never logged in to Bridgy. But even if that was a fluke, we still would've expected Tantek's person tag of himself to make it through.

**Comment by kylewm** [comment] 2016-01-19 17:55
I mentioned on IRC that person tags used to not work without a location (["You cannot specify this field without also specifying a place."](https://developers.facebook.com/docs/graph-api/reference/user/feed#publish), though the same caveat does not exist on the photos page) and I was surprised when they started working. Maybe Facebook fixed the "bug" that was letting us do it temporarily.

**Comment by snarfed** [comment] 2016-01-19 17:57
[here's the publish log.](https://brid.gy/log?start_time=1453187164&key=aglzfmJyaWQtZ3lyWQsSDVB1Ymxpc2hlZFBhZ2UiMmh0dHA6Ly90YW50ZWsuY29tLzIwMTYvMDE4L3Q0L3czY2FiLW1lZXRpbmctaGF3YWlpDAsSB1B1Ymxpc2gYgICAgIDkkQoM)

[from IRC](http://indiewebcamp.com/irc/2016-01-19#t1453225254203):

> snarfed looking at the log, this is what we sent to facebook:
> snarfed url=https://scontent-sjc2-1.cdninstagram.com/hphotos-xtf1/t51.2885-15/e35/12407429_887813537998827_121176936_n.jpg&message=One week ago, @W3CAB meeting in #Hawaii. I blame @Nov_Project for the #straightface reflex. #latergram #nofilter\n\n(Originally published at: http://tantek.com/2016/018/t4/w3cab-meeting-hawaii)&tags=[{"tag_uid": "100000802747500"}, {"tag_uid": "735170173"}, {"tag_uid": "214611"}, {"tag_uid": "538464812"}, {"tag_uid": "692216758"}]
> snarfed so that included five person tags
> snarfed so evidently FB rejected them all?
> snarfed (we can load those user ids' profiles to confirm that they're the right people)
> kylewm well 214611 is definitely tantek

**Comment by snarfed** [comment] 2016-01-19 18:04
the `tags` param format with url-encoded JSON seems odd, but evidently it's right. e.g. [this older FB publish with successful person tags](https://brid.gy/log?start_time=1447900406&key=aglzfmJyaWQtZ3lySwsSDVB1Ymxpc2hlZFBhZ2UiJGh0dHBzOi8vc25hcmZlZC5vcmcvMjAxNS0xMS0xOF9od2NfMgwLEgdQdWJsaXNoGICAgICAgIAKDA) used the same format: 

```
url=https://i1.wp.com/snarfed.org/w/wp-content/uploads/2015/11/wpid-wp-1447899561388.jpg?w=696
  &message=Celebrating Homebrew Website Club\xe2\x80\x99s 2nd anniversary....
  &tags=[{"tag_uid": "36802236"}, {"tag_uid": "214611"}]
```

**Comment by snarfed** [comment] 2016-01-19 18:14
the FB API call is a POST to `/USERID/photos`, and [its docs confirm this format](https://developers.facebook.com/docs/graph-api/reference/v2.2/photo/tags#Creating). [StackOverflow too.](http://stackoverflow.com/a/12563464/186123))

plus, we got a 200 from the API request, and FB usually returns non-2xx with error details if we give it a bad parameter; it doesn't usually silently ignore.

**Comment by snarfed** [comment] 2016-01-19 18:23
tantek's access token includes the `publish_actions` permission, which should be enough.

**Comment by snarfed** [comment] 2016-01-21 00:47
i don't have any new leads on this, and i haven't found any other recent person-tagged facebook publish attempts to compare against. :/ @tantek, definitely let us know if you end up trying again!

**Comment by snarfed** [comment] 2016-01-24 17:51
@tantek retried and person tags went through again, surprisingly even more than we thought. details:
https://github.com/snarfed/bridgy/issues/568#issuecomment-174248236

we still don't understand why tags didn't work the last time, but it's looking like our code is working naively at least, and Facebook's tagging API is either unpredictable or more complicated than we thought.

so, I'm tentatively (re)closing this. we can keep collecting data points on the complexities in #568.

**Closed by snarfed** 2016-01-24 17:51 UTC
Labels: now, publish, SWAT0
