### ISSUE TITLE
No webmention targets for Twitter

### ISSUE THREAD

**Issue by azzamsa** [snarfed/bridgy#956] opened 2020-07-11 21:16 UTC
My mastodon account works without any trouble. I just need to add my blog link in my profile.

but Twitter always said "No webmention targets" even if I've put my blog link in profile page & description.

Thank you for birdgy.

**Comment by snarfed** [comment] 2020-07-11 23:30
thanks for the kind words!

i see three likes on https://brid.gy/twitter/azzamsyawqi that bridgy did try to send webmentions for, but the links to your site in the tweets both return 404 not found. specifically:
* https://twitter.com/azzamsyawqi/status/1228915415264268289 links to https://azzamsa.com/blog/gitpython-start , which 404s
* https://twitter.com/azzamsyawqi/status/1269461988049993728 links to https://azzamsa.com/blog/scripts-el/ , which 404s

looks like you changed your blog permalinks from `/blog/` to `/n/` at some point, and those old URLs no longer work. if you redirect them to the new URLs, then click retry on bridgy, it might be able to send the webmentions.

**Comment by azzamsa** [comment] 2020-07-12 00:12
Hi, I am aware of that.

I've tried to post new links:
- https://twitter.com/azzamsyawqi/status/1282002276526157824
- https://twitter.com/azzamsyawqi/status/1282002169072193538

to valid destination
- https://azzamsa.com/n/id/pengujian-tju/
- https://azzamsa.com/n/daily-apps/

and I've put my blog in the profile section and profile:

![image](https://user-images.githubusercontent.com/17734314/87236110-f9ef0980-c40e-11ea-9c86-cc2d80e6b1a2.png)

But still

![image](https://user-images.githubusercontent.com/17734314/87236113-ff4c5400-c40e-11ea-9f26-2f37fd84dd1d.png)

---

But the mastodon bridge works just fine.

**Comment by snarfed** [comment] 2020-07-12 00:17
ah, ok. looks like this is just bad UI on bridgy's part. those three are expected, since they're your original POSSEd tweets, not likes or retweets or replies. i should hide the _No webmention targets_ for original tweets like that since it's expected. i'll do that. thanks for filing!

**Comment by azzamsa** [comment] 2020-07-12 00:34
your like is sent.

![image](https://user-images.githubusercontent.com/17734314/87236309-f1e49900-c411-11ea-9680-cdf6510e3a64.png)

but, do you have any idea why my comment is not sent?
I've tried to craw-discover-retry, doesnt work https://twitter.com/azzamsyawqi/status/1282108488475279361

**Comment by snarfed** [comment] 2020-07-16 18:07
oops, sorry, shouldn't have closed. i updated the UI to omit _No webmention targets_ for POSSEd posts, as in your original question. you can see the results on https://brid.gy/twitter/azzamsyawqi .

i still need to look at the comment you mentioned most recently.

**Comment by azzamsa** [comment] 2020-07-16 20:45
Yes. I tried to explore more.

![image](https://user-images.githubusercontent.com/17734314/87720890-d39ae680-c7df-11ea-9cda-7ad927970250.png)

1. both the green mark is comment and like, they are sent.
2. but the non-green mark is my own comment, marked as "no target". is this expected? because it's my own thread?

Thread: https://twitter.com/azzamsyawqi/status/1282002276526157824

**Comment by snarfed** [comment] 2020-07-17 00:06
hi @azzamsa! sorry for the trouble. i don't yet know why your "Love those FOSS apps!" reply wasn't sent. bridgy does generally include your own replies. i'll try to figure it out eventually.

**Comment by azzamsa** [comment] 2020-07-18 22:55
Tried reply and likes from other account, works fine. Sorry currently can't help with bridgy code debugging.

![image](https://user-images.githubusercontent.com/17734314/87863340-5ceb1e00-c984-11ea-9e35-eeb0b98b6202.png)

**Comment by snarfed** [comment] 2020-11-29 20:20
i wasn't able to reproduce the missing "Love those FOSS apps!" reply. any luck on your side? assuming not, so i'm tentatively closing, but feel free to reopen!

**Closed by snarfed** 2020-11-29 20:20 UTC
