### ISSUE TITLE
Bridgy missed some replies 

### ISSUE THREAD

**Issue by hyde-stevenson** [snarfed/bridgy#951] opened 2020-06-09 07:24 UTC
Hello, 

It looks like sometimes bridgy does miss some replies. Here's an example : 

https://lazybear.io/posts/cafes/
and the mastodon thread : 
https://lazybear.social/web/statuses/104295432357160190

Or here : 
https://lazybear.io/posts/why-does-even-capslocks-exist/
and the https://lazybear.social/@hyde/104245318260200443

If you have any idea ?

**Comment by snarfed** [comment] 2020-06-09 14:48
hmm, sorry for the trouble! looks like it's not due to [any of the usual reasons.](https://brid.gy/about#missing) i'll look soon.

btw, [your bridgy user page](https://brid.gy/mastodon/@hyde@lazybear.social) thinks your mastodon account is locked, ie private. it's obviously not now, but i'm guessing it was when you first signed up for bridgy? you might want to log into bridgy with mastodon again to clear that up. (i don't think it's the cause of this problem though.)

**Comment by hyde-stevenson** [comment] 2020-06-09 15:13
No worries. 

It said locked because I was approving followers requests.  Indeed, it's gone once logged in again. 

I'll check the reasons too on the page you mentioned. 

Thanks.

**Comment by snarfed** [comment] 2020-06-11 00:56
never mind, i was wrong. confirmed just now, bridgy already does this merging when it gets multiple copies of a reply.

**Comment by hyde-stevenson** [comment] 2020-06-11 09:17
Hello thanks for checking ... but I guess other people have the same kind of issues, don't they ?

**Comment by armingrewe** [comment] 2020-06-11 10:37
Probably. I think I've had the odd case where somewhere in a long chain some replies didn't get picked up. Must admit I've not really worried about it, so don't have any examples to hand and never raised it.

**Comment by snarfed** [comment] 2020-11-29 20:21
hey @hyde-stevenson, i've tried to reproduce this, but haven't had any luck. is it still happening to you?

**Comment by snarfed** [comment] 2021-02-26 17:03
I tried putting the two Mastodon threads you mentioned into the _Resend for post_ box on https://brid.gy/mastodon/@hyde@lazybear.social just now, and it found and sent all the missing replies. I'm not sure what happened originally, but I wonder if the Mastodon API was flaky. There's also https://github.com/tootsuite/mastodon/issues/11029, but that should only matter when there's a very large number of replies, and there weren't here.

Regardless, whatever happened here, this may be fixed now. Feel free to use _Resend for post_ to fill in any other missing replies. Thanks again for filing!

**Closed by snarfed** 2021-02-26 17:03 UTC
Labels: listen
