### ISSUE TITLE
icon font gives 404

### ISSUE THREAD

**Issue by jonnybarnes** [snarfed/bridgy#700] opened 2016-09-23 11:55 UTC
`https://brid.gy/fonts/glyphicons-halflings-regular.woff2` is the URI returning 404

**Comment by snarfed** [comment] 2016-09-23 14:25
thanks for the heads up! fortunately the woff 1 file is loading fine, so nothing's broken, but still worth fixing.

**Comment by snarfed** [comment] 2016-09-23 14:25
caused by snarfed/oauth-dropins@b4a504e0179f72c15b691b110e5f6dfe67de0660

**Comment by snarfed** [comment] 2016-09-28 21:31
fixed by snarfed/oauth-dropins@fec508e56d726ecbc94fcd14028f8bd32611c916

**Closed** 2016-09-28 21:36 UTC
Labels: now
