### ISSUE TITLE
Should twitter profile pictures be expected to load?

### ISSUE THREAD

**Issue by wholewheattoast** [snarfed/bridgy#564] opened 2015-12-04 07:04 UTC
All twitter profile icons do not appear to load correctly.

"Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains."

![screenshot 2015-12-03 23 01 19](https://cloud.githubusercontent.com/assets/231390/11583732/e2f96760-9a11-11e5-9bf1-653003bb0526.png)

**Comment by kylewm** [comment] 2015-12-04 07:40
I *think* the broken images and the error message are unrelated. I get the same error in my console even though the images load, and the error seems to be coming from a Facebook JS library.

Can you check in about:config whether you have `privacy.trackingprotection.enabled` enabled? (or if you are running in a Private Window). I noticed Firefox started blocking hotlinked FB and Twitter images recently if tracking protection is on.

**Comment by snarfed** [comment] 2015-12-04 18:13
thanks for filing! you're definitely not alone; i've seen this before too. it's pretty rare for me, though, and refreshing always fixes it. 

anecdotally, i tried loading https://brid.gy/twitter/wholewheattoast in a few different browsers/OSes just now. firefox and safari on os x and safari on android all loaded the profile picture ok. chrome on os x didn't load it at first, but did on refresh.

if it's reproducible for you, @kylewm's guess sounds likely.

**Comment by wholewheattoast** [comment] 2015-12-05 08:41
@kylewm I did have 'privacy.trackingprotection.enabled'.  Sisabling and refreshing page did not cause icons to load.  FF Dev seems to be the only browser on this machine that I currently see the issue. (mac 0S: Current versions of Chrome, Safari, and FF tested).

**Comment by snarfed** [comment] 2015-12-05 16:08
aha, this is only in FF Dev? i don't have much experience with that one. if you do, want to try debugging? i think these images are all pretty plain vanilla `<img>`tags, so I'm not sure exactly what we'd change on our end, apart from mirroring every twitter profile picture ourselves. (nope :P)

**Comment by snarfed** [comment] 2015-12-10 01:14
tentatively closing since this is only in FF Dev. @wholewheattoast feel free to open if you want to keep digging!

**Closed by snarfed** 2015-12-10 01:14 UTC
