### ISSUE TITLE
Tumblr Rewriting URLs

### ISSUE THREAD

**Issue by antipolar** [snarfed/bridgy#609] opened 2016-01-21 07:18 UTC
Tumblr is now rewriting all outbound links to a redirect page. In effect breaking whatever chance we had for web mention support. You can use the source url to some extent but this method is rigid and cannot be changed on a post by post basis. The redirect link is fairly simple (http://t.umblr.com/redirect?z=URL&t=TOKEN). However, it still wouldn't solve the bigger problems of the link back that is necessary for a web mention.

**Comment by snarfed** [comment] 2016-01-21 15:09
ugh. thanks for reporting! you're right, parsing these redirect links should be straightforward. we'll do that.

funny, looking at https://brid.gy/tumblr/antipolar.tumblr.com , bridgy actually reports that some of your outgoing webmentions still succeeded, e.g. to quill.p3k.io and codemonkey.known.com, but i expect that's just because they're processing async and returning 202: https://indiewebcamp.com/webmention-spec#Receiving_Webmentions . their verifications probably still failed.

i see your bridgy publish fix, too. it's not working because of #590. worth trying though!

**Comment by antipolar** [comment] 2016-01-21 15:34
That is weird, because I had about 5 or 6 fail before those (even when I tried to manually send the web mention using Telegraph). Hmm, there seems to be some kind of disconnect. I've checked the RSS and the URLs are not encoded in the RSS only in the HTML version of the articles.

**Comment by snarfed** [comment] 2016-01-21 17:14
oh interesting, you're right about the RSS, which is what superfeedr (and therefore bridgy) uses. nice sleuthing. may be just an oversight on tumblr's part that they'll eventually fix. we'll see.

**Comment by snarfed** [comment] 2016-01-21 17:16
(and yeah, the backlink check is what i meant by "their verifications probably still failed." quill and known only succeeded because they do that check out of band.)

**Comment by snarfed** [comment] 2016-01-21 17:26
i don't see a good option for this yet. :/ here are some bad ones though!
* run a proxy that resolves t.umblr.com links and adds u-url links that point to the original page. use this proxy for source URLs instead of the original pages. (ugh. not excited about this.)
* change the webmention spec and current implementations to follow redirects for all links on the source page before looking for a link to the target. (this is a totally unreasonable burden to impose on webmention receivers. we shouldn't actually do this. :P)
* change the webmention spec and current implementations to accept target links that are url-encoded and inside other links or text. (not a burden, but seems like a bad idea in all sorts of ways. we probably shouldn't do this either.)
* do nothing. i doubt anything will change on tumblr's end, which would mean outgoing webmentions for tumblr are dead. :/

cc @aaronpk, if only for entertainment value.

**Comment by snarfed** [comment] 2016-01-21 17:27
btw, just for the record, *incoming* webmentions on tumblr still work fine. this only breaks outgoing ones.

**Comment by aaronpk** [comment] 2016-01-21 17:43
This actually isn't as bad as it sounds. Right now, you can send webmentions with these URLs and still fall within the spec, but only because the spec doesn't specify criteria on whether a URL should be "[supported by the receiver](https://www.w3.org/TR/webmention/#request-verification)".

If a tumblr post links to aaronparecki.com, the trick is you'd send a webmention with a target URL that is tumblr's new redirect URL. **If** my webmention endpoint first follows redirects on the target link before checking if it's one of my URLs, then I would accept the webmention without any additional work. 

Note that in order for me to support receiving webmentions on my own URLs that have changed, I need to basically do this anyway. When I push out the new version of my site, all my URLs will be changing, but I still want to receive webmentions to the old URLs so I will actually be doing exactly this.

**Comment by antipolar** [comment] 2016-01-22 01:23
@snarfed I don't think following the redirects would be too much effort on the webmention reciever. A proper redirect will throw a HTTP/1.0 301 header with the URL to the new page, which you would then match against your permalink. I know it adds extra work on the webmention receiver, but it could relieve any future problems if another publisher decides to use redirects (for security/spam/whatever control reasons).

@aaronpk But in that scenario you're treating the redirect url as target of the webmention. That just seems wrong by practice, as the redirect was not the intentional target of the webmention. It also depends on the webmention endpoint following the redirect. Although, this would lessen the work done by the webmention receiver. It's skirting around the bigger issue of redirects in webmentions, which would be ideally defined in the spec. 

Aaron's solution would work for the interim. But I think this is definitely an issue that needs to be brought up to the spec writers.  I submitted a support ticket on Tumblr asking for at least a reason why they implemented the redirects (and also if they would consider a way to turn them off on a blog-by-blog basis). However, I highly doubt they're going to respond to it with anything but a "Thank you for your comment" reply.

**Comment by snarfed** [comment] 2016-01-22 01:58
@antipolar the problem is that the average web page has a *lot* of links. here are a few examples:

```
hell:~> curl http://antipolar.tumblr.com/post/137722020915/garbage-pail-canidates | grep -c http
93
hell:~> curl http://aaronparecki.com/articles/2015/12/07/1/letsencrypt | grep -c http
101
hell:~> curl https://snarfed.org/2013-03-02_mac_os_x | grep -c http
244
```

that overcounts, granted, but it's a decent approximation. even if we're generous and say the average webmention source only has 50 links, it's still a substantial burden to resolve all of them.

**Comment by antipolar** [comment] 2016-01-22 02:17
@snarfed Found this in the Editor's Draft of the Webmention Spec:

>**2.2.2 Webmention Verification**
>
>Webmention verification should be handled asynchronously to prevent DoS attacks.
>
>If the receiver is going to use the webmention in some way, (displaying it as a comment on a post, 
>incrementing a "like" counter, notifying the author of a post), then it **must** perform an HTTP GET 
>request on source, and **follow any HTTP redirects** (up to a self-imposed limit such as 20) to confirm 
>that it actually links to target.

[W3C Editor's Draft 17 December 2015](http://webmention.net/draft/)

**Comment by snarfed** [comment] 2016-01-22 04:45
> @snarfed Found this in the Editor's Draft of the Webmention Spec

sure! that's for the source page itself, though, which there's only one of, and afaik most wm receivers already follow redirects for. we're talking about links *inside* the source page here.

**Comment by aaronpk** [comment] 2016-01-22 15:19
@antipolar you happen to be talking to the editor of the spec! :smile: 

Good specs tend to describe the working consensus of implementations, rather than being prescriptive. If this problem happens often enough, people who implemented webmention receivers will start following the redirect since it will benefit them, at which point it will be a no-brainer to add it to the spec.

I will raise an issue on the spec about this since it definitely is worth mentioning specifically! At the very least we should try to survey existing implementations to see who follows redirects of the target currently.

**Comment by snarfed** [comment] 2016-01-22 17:41
btw thanks for the resolving target idea earlier @aaronpk! i may do that for bridgy publish, which would at least keep it working with this change. wouldn't fix interactive, but oh well.

**Comment by snarfed** [comment] 2016-01-22 18:45
ugh. evidently t.umblr.com redirects use `meta http-equiv="refresh"`, not 301/302, and only for `GET`. they 404 `HEAD` requests! example below.

bleh. i'm now way less motivated to make this work.

```
hell:~> curl -vI 'http://t.umblr.com/redirect?z=https%3A%2F%2Ftwitter.com%2Fscottaolson%2Fstatus%2F689272343324004352&t=MzA3YjliOTgxZDNiNDI4ZTFmNjI1M2Q4MzVkOGQ0OGUxMjY0NWM1NCxCOE9JaXhYUQ%3D%3D'
*   Trying 66.6.43.34...
* Connected to t.umblr.com (66.6.43.34) port 80 (#0)
> HEAD /redirect?z=https%3A%2F%2Ftwitter.com%2Fscottaolson%2Fstatus%2F689272343324004352&t=MzA3YjliOTgxZDNiNDI4ZTFmNjI1M2Q4MzVkOGQ0OGUxMjY0NWM1NCxCOE9JaXhYUQ%3D%3D HTTP/1.1
> Host: t.umblr.com
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
< Content-Length: 182
Content-Length: 182
< Connection: close
Connection: close

hell:~> curl -v 'http://t.umblr.com/redirect?z=https%3A%2F%2Ftwitter.com%2Fscottaolson%2Fstatus%2F689272343324004352&t=MzA3YjliOTgxZDNiNDI4ZTFmNjI1M2Q4MzVkOGQ0OGUxMjY0NWM1NCxCOE9JaXhYUQ%3D%3D'

*   Trying 66.6.43.34...
* Connected to t.umblr.com (66.6.43.34) port 80 (#0)
> GET /redirect?z=https%3A%2F%2Ftwitter.com%2Fscottaolson%2Fstatus%2F689272343324004352&t=MzA3YjliOTgxZDNiNDI4ZTFmNjI1M2Q4MzVkOGQ0OGUxMjY0NWM1NCxCOE9JaXhYUQ%3D%3D HTTP/1.1
> Host: t.umblr.com
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=utf-8
< Content-Length: 393
< Connection: close
< 
<noscript><meta name="referrer" content="origin"><meta http-equiv="refresh" content="0;URL=https://twitter.com/scottaolson/status/689272343324004352"></noscript><meta name="referrer" content="origin"><title>https://twitter.com/scottaolson/status/689272343324004352</title><script>window.opener = null; location.replace("https:\/\/twitter.com\/scottaolson\/status\/689272343324004352")</script>hell:~/src/oauth-dropins/oauth_dropins{master}> 

hell:~>
```

**Comment by kylewm** [comment] 2016-01-23 23:20
> hell:~>

how apropos

**Comment by snarfed** [comment] 2016-02-04 18:10
i'm now considering special casing the `t.umblr.com` URLs and parsing the destination links out of them. we'd need to do this both for outgoing webmentions and for the publish backlink check.

here's a complete example from http://antipolar.tumblr.com/post/137614052765/bernie-sanders . we just need to grab the `z` param.

`<a href="http://t.umblr.com/redirect?z=https%3A%2F%2Fbrid.gy%2Fpublish%2Ftwitter&amp;t=YmZkMzQyODJmYjQ5ZmEzNDNlMWI5YmZhYmQ2MWI4NDcyNDNlMjNhOCxCOE9JaXhYUQ%3D%3D"></a>`

cc @Belp-audio

**Comment by Belp-audio** [comment] 2016-02-04 18:32
That would be fantastic. +1!

**Comment by snarfed** [comment] 2016-02-08 21:29
hey @antipolar, @Belp-audio, any luck with the fix that went out a few days ago?

**Comment by snarfed** [comment] 2016-02-11 00:59
@Belp-audio reported that it worked!

**Closed by snarfed** 2016-02-11 00:59 UTC
Labels: blogs, publish
