### ISSUE TITLE
Post To Twitter from  Wordpress error

### ISSUE THREAD

**Issue by digiSal** [snarfed/bridgy#1140] opened 2022-03-07 06:53 UTC
Hello, I hadnt blogged in forever but i sent one and i got an error with an empty log file. And when I tried to manually send the post via the bridgy site it has been stuck in processing for 24 hours. 

here is the twitter page
https://brid.gy/twitter/digiSal
siteurl is digisal.com

**Comment by snarfed** [comment] 2022-03-07 17:30
Hi, sorry for the trouble! Looks like the root cause here is the mf2 markup on your site. You have `h-entry` on your `body`, which tells Bridgy that everything on the page is part of your post, including the webmentions in the left sidebar. Their profile pictures are marked up with `u-photo`, and one of them (`https://pbs.twimg.com/profile_images/3622692489/2a37bbc95e0ec9452570851033b0811b.jpeg`) 404s. Usually Bridgy wouldn't care, but the markup says it's part of your post, so Bridgy refused to send it to Twitter incomplete.

The fix is to move `h-entry` further down in your HTML to enclose just your post content, not the whole page.

I'll look at the "stuck in processing" one though, Bridgy should definitely handle that better!

**Comment by digiSal** [comment] 2022-03-08 06:56
Hmm not sure how to move that h-entry since I am on wordpress and i am using the indieweb plugin and their wiki says to place it in a sidebar
https://indieweb.org/Getting_Started_on_WordPress#:~:text=on%20the%20wiki.-,Online%20Identity%20using%20h%2Dcard,-%5Bedit%5D

when i remove it from the sidebar and then try to validate the site on indiewebify.me it complainss that there is no h-entry. any other ideas?

maybe its that 404 thats killing it but that profile pic is coming from a webmention twitter reply i believe. will look into it.

**Comment by snarfed** [comment] 2022-03-08 14:35
This is out of scope of Bridgy itself, but @dshanske and the #wordpress channel on https://indieweb.org/discuss may be able to help!

**Closed by snarfed** 2022-03-08 14:35 UTC
